### ISSUE TITLE
MSVC does not define THRUST_CPP_DIALECT correctly

### ISSUE THREAD

**Issue by bjude** [thrust/thrust#1030]
MSVC always defines __cplusplus as 199711L, regardless of the standard mode, which means that THRUST_CPP_DIALECT will always be set to 2003.

#1028 attempted to work around this by using _MSVC_LANG to set THRUST_CPP_DIALECT correctly but ran into problems with MSVC's standard compliance on older versions MSVC regarding expression SFINAE.

**Comment by peterjc123** [comment]
If this is the case, maybe we could apply `/Zc:__cplusplus` to fix that.

**Comment by allisonvacanti** [comment]
Just to keep this issue updated -- there's a patch on the way that will update the dialect detection to use `_MSVC_LANG` instead of `__cplusplus` when defined and deprecate support for MSVC compilers that don't define it. This will effectively resolve this issue.

**Comment by allisonvacanti** [comment]
This has been addressed in #1089.
