### ISSUE TITLE
Neccessity of cuda_cub::synchronize in merge_sort

### ISSUE THREAD

**Issue by mseagrief** [thrust/thrust#1034]
Is the cuda_cub::synchronise call in merge_sort necessary?

https://github.com/thrust/thrust/blob/324243f6bb70687aeaeb2419193a335648c5869d/thrust/system/cuda/detail/sort.h#L1316

I'm using `thrust::sort` on an array of `float4` elements with a custom comparator. The goal is to have the sort operation be entirely asynchronously to the host and pick up the result later. The sort is part of a larger block of other operations all being launched asynchronously in a single stream.

I'm already using a custom allocator that wraps up `cub::CachingDeviceAllocator` to avoid `cudaMalloc/cudaFree` stalls.

From what I can see synchronise call is the last step the sort performs. My expectation would be that when using a stream any necessary synchronisation would be the caller's responsibility (i.e. `cudaStreamSynchronize/cudaDeviceSynchronize`).

For now, I've implemented a custom `execution_policy` that simply does a `cudaGetLastError` call in the `synchronize_stream` function without the `cudaStreamSynchronize` call in the default implementation. I've been through the output thoroughly and not seen any unexpected side effects.

```
struct point_compare
{
	__device__ __host__
		bool operator()(const float4& a, const float4& b)
	{
		return a.z>b.z;
	}
};
```

`float4` is from the CUDA headers in vector_types.h

**Comment by griwes** [comment]
`thrust::sort` is a synchronous algorithm. For an asynchronous version, please use `thrust::async::sort` (note that it currently only works on the device of the CUDA backend).

We're currently lacking proper documentation for the asynchronous algorithms, but we are working on it.

The async algorithms are also already using the new Thrust 10.1 caching memory resources.
