### ISSUE TITLE
[OpenMP] Avoiding false sharing during thrust::transform

### ISSUE THREAD

**Issue by rgov** [thrust/thrust#1066]
Suppose I run the following with the OpenMP device system setting on a multi-core system:

```c++
int A[100];
thrust::transform(
        thrust::counting_iterator<int>(0),
        thrust::counting_iterator<int>(100),
        A,
        [] (int i) { return 3; }
}
```

If the first thread modifies `A[i]`, this will invalidate the cache line across all cores, so that before another thread modifies `A[i+1]`, it needs to re-fetch the cache line, i.e., there would be [false sharing](https://software.intel.com/en-us/articles/avoiding-and-identifying-false-sharing-among-threads) between the threads.

Does Thrust automatically address this? Or what can I do to try to order array accesses so that they are further apart? E.g., if the counting iterator emitted `[0, 64, 1, 65, 2, 66, 3, 67, ...]` for a 2-core system that would probably work much better.

**Comment by jaredhoberock** [comment]
> Does Thrust automatically address this?

No

>  Or what can I do to try to order array accesses so that they are further apart? E.g., if the counting iterator emitted [0, 64, 1, 65, 2, 66, 3, 67, ...] for a 2-core system that would probably work much better.

Try creating some sort of [striding iterator](https://github.com/thrust/thrust/blob/master/examples/strided_range.cu) instead of using a `counting_iterator`.

**Comment by rgov** [comment]
I did a quick experiment:

```c++
int main(void) {
    std::vector<int> indices(100);
    for (int i = 0; i < indices.size(); i ++) {
        indices[i] = 0;
    }
    
    std::vector<int> values(100);
    thrust::transform(
        thrust::device,
        indices.begin(),
        indices.end(),
        values.begin(),
        [] (int i) { return omp_get_thread_num(); }
    );

    for (int i = 0; i < values.size(); i ++) {
        std::cout << values[i] << " ";
    }
    std::cout << std::endl;

    return 0;
}
```

This shows me which thread is being used to fill in which array element. What I found:

```
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 
```

This suggests to me maybe the striding iterator isn't necessary?

**Comment by jaredhoberock** [comment]
Thrust just calls something equivalent to this:

    #pragma omp parallel for
    for(int i = 0; i < n; ++i)
    {
      f(i);
    }

So, Thrust doesn't do anything fancy and just allows OpenMP to assign iterations to threads itself. In this case, it looks like it's already doing what you need.

**Comment by rgov** [comment]
Ah ok, thanks. Is this something I need to care about for the CUDA backend, then?
