### ISSUE TITLE
Use pointer to previously allocated memory for temporary storage in sort

### ISSUE THREAD

**Issue by estebanpw** [thrust/thrust#1110]
I am working on a CUDA program that uses thrust to sort keys and values. In particular, I am using a memory pool that is allocated at the beginning of the program as a char array in the GPU, and I manage this pool with different pointers so to avoid a lot of CudaMallocs throughout the execution. I was wondering if there is way to tell thrust to use a given pointer (that in this case would point to a section of the memory pool) for the temporary storage required when sorting. I have done this previously with the CUB library in the following way:

`cub::DoubleBuffer<uint64_t> vector_of_keys(keys, keys_buffer);`
`cub::DoubleBuffer<uint64_t> vector_of_values(values, values_buffer);`
`cub::DeviceRadixSort::SortPairs(..., ..., vector_of_keys, vector_of_values, n);`

where `keys_buffer` and `values_buffer` are pointers to the memory pool that I have previously allocated in the GPU.

I have been searching and the closest I have found is this:

https://github.com/thrust/thrust/blob/master/examples/cuda/custom_temporary_allocation.cu

But I wonder if there is a more direct way to "just pass a pointer" such as like this:

`thrust::sort_by_key(keys, keys + n, values, keys_buffer, values_buffer);`

Thank you very much for your time,
Esteban

**Comment by griwes** [comment]
No, there's no hooks for allowing Thrust use a different source of temporary storage other than explicitly providing an allocator (or a memory resource) using the execution policy as shown in the example you've found.

**Comment by estebanpw** [comment]
Thanks for the info
