### ISSUE TITLE
CODE_OF_CONDUCT.md?

### ISSUE THREAD

**Issue by codereport** [thrust/thrust#1133]
Does `thrust` have a COC? If so, we should add a `CODE_OF_CONDUCT.md`. If not, one should be added similar to the `RAPIDS` [COC](https://github.com/rapidsai/cudf/blob/branch-0.14/CODE_OF_CONDUCT.md)

**Comment by brycelelbach** [comment]
Yes, of course we need to do this! Thanks for calling attention to it.

Whatever we do for Thrust we should also do for CUB and libcu++.

I'm think we should just use the [RAPIDS CoC](https://docs.rapids.ai/resources/conduct/). No need to reinvent the wheel. @allisonvacanti and @griwes please review it and let me know if you agree.

The RAPIDS CoC is based on the [Contributor Covenant Version 1.4[(https://www.contributor-covenant.org/). @codereport, do you know what changes if any were made to the version in RAPIDS?

My preference would be to have `CODE_OF_CONDUCT.md` contain the full text of the Code of Conduct in Markdown form (RAPIDS `CODE_OF_CODUNCT.md` links to the one in the docs).

We'll need an email address for reporting conduct violations too. I think the simplest solution there is `thrust-conduct@nvidia.com`, `cub-conduct@nvidia.com`, and `libcudacxx-conduct@nvidia.com`.

@codereport would you be willing to prepare a pull request against Thrust and CUB for this? @griwes will take care of landing it in libcu++.

**Comment by allisonvacanti** [comment]
+1, The proposed version sounds good to me.

**Comment by codereport** [comment]
> @codereport would you be willing to prepare a pull request against Thrust and CUB for this?
Yep, will do.
