### ISSUE TITLE
Add developer build instructions to README.md

### ISSUE THREAD

**Issue by allisonvacanti** [thrust/thrust#1160]
Since the Thrust repo contains files for a few different build systems, it's not clear to new developers which should be used.

We should add section to the README.md that details the build process for contributors, including dependencies, general CMake configuration steps, and Thrust-specific CMake options.

**Comment by allisonvacanti** [comment]
We'll also need to update https://github.com/thrust/thrust/wiki/Developer-Information to point at the README once this is done.

**Comment by allisonvacanti** [comment]
Relevant to #1164.

**Comment by hwinkler** [comment]
Great, thanks for doing this.

A few remarks after making my first unit test contribution.

a) I am not CMake-savvy. It wasn't hard to figure out but the coming cookbook will be welcome. 

b) I'm never on a supported configuration for the CUDA toolkit. I always need to set CCBIN, NVCC, and the path to Thrust. I discovered the relevant variables by looking in the CMakeLists.txt and by trial and error.

c) I left my desk for a few hours, came back and the tests build was 40% complete. `make -j` is important.

d) Gonna need lots of memory  -- my 32GB laptop managed OK, but Linux killed a process to make room.

e) I'm sure I didn't need to build everything, but at first I didn't realize what a gargantuan undertaking it was, or that I could've built just the target I needed.. After getting past the initial minor hurdles, the system built everything without a hitch. Impressive. Feels solid. Great work.

**Comment by allisonvacanti** [comment]
Thanks for the feedback! I'll add some notes about the requirements to set expectations -- CUDA header library test suites are definitely a beast to compile.
