### ISSUE TITLE
How to build without CUB?

### ISSUE THREAD

**Issue by yurivict** [thrust/thrust#1180]
On FreeBSD CUB isn't available because CUDA isn't available.

How to eliminate the use of CUDA, and use CPU computations, for example?

**Comment by allisonvacanti** [comment]
You can change the device system to OpenMP or TBB for parallel CPU computation, or CPP for CPU serial by defining `THRUST_DEVICE_SYSTEM` at compile time. See https://github.com/thrust/thrust/wiki/Device-Backends for how to do this manually.

If you're using a (very) new version of Thrust from CMake, there is a find module that simplifies things: https://github.com/thrust/thrust/blob/master/thrust/cmake/README.md.

Feel free to reopen this if those docs aren't sufficient.
