### ISSUE TITLE
Cleanup unused helper structs in thrust/system/cuda/detail/util.h

### ISSUE THREAD

**Issue by allisonvacanti** [thrust/thrust#1187]
`transform_output_iterator_t`, `transform_triple_of_input_iterators_t`, and `static_integer_iterator` do not seem to be used anywhere in Thrust. Survey the helper types in this file and remove all that are unused.

**Comment by allisonvacanti** [comment]
(As discussed in #1177)

**Comment by jaredhoberock** [comment]
I'll take this one
