### ISSUE TITLE
CMAKE_CXX_STANDARD support for NVC++

### ISSUE THREAD

**Issue by dkolsen-pgi** [thrust/thrust#1200]
The CMake customizations for NVC++ don't include converting the CMAKE_CXX_STANDARD variable into the correct command-line option for that compiler.  That results in test failures due to NVC++ being run at the wrong C++ language level.  The CMake customizations need to handle that correctly (at least until NVC++ support is added to CMake for real).

**Comment by brycelelbach** [comment]
I think this is fixed.
