### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by allisonvacanti** [thrust/thrust#1203]
We've been discussing this for a while internally, but the last point of uncertainty was the new naming convention. Github itself is switching to use the less problematic name `main` by default, so let's go with that.

We're currently checking with some stakeholders to coordinate the timing of this, but are planning the change in the future.

**Comment by allisonvacanti** [comment]
The `main` branch has been create and is now the default. Update local clones with:

```
git submodule update origin
git checkout --track origin/main
```

Assigning @brycelelbach -- I'll let you decide whether to close this or leave it open until the github pages issue is fixed.

**Comment by brycelelbach** [comment]
Let's close it.
