### ISSUE TITLE
Cub commit not aligned with THRUST master

### ISSUE THREAD

**Issue by stefanozampini** [thrust/thrust#1204]
zampins@vulture:~/Devel/thrust$ git submodule update --init
Submodule 'cub' (https://github.com/thrust/cub.git) registered for path 'dependencies/cub'
Cloning into 'dependencies/cub'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 33125 (delta 11), reused 42 (delta 4), pack-reused 33067
Receiving objects: 100% (33125/33125), 16.74 MiB | 10.48 MiB/s, done.
Resolving deltas: 100% (28931/28931), done.
Checking connectivity... done.
fatal: reference is not a tree: fa789aa1eaffb88c0175b7f31d91148ff6fcb943
Unable to checkout 'fa789aa1eaffb88c0175b7f31d91148ff6fcb943' in submodule path 'dependencies/cub'

**Comment by allisonvacanti** [comment]
Thanks for the report -- I'll get this fixed asap.

**Comment by allisonvacanti** [comment]
Should be all set now.

**Comment by stefanozampini** [comment]
thanks for the prompt action
