### ISSUE TITLE
Uninitialized variable being used in allocator_traits.inl

### ISSUE THREAD

**Issue by mikoro** [thrust/thrust#1206]
CUDA 11 RC, Microsoft Visual Studio Community 2019 Version 16.5.4

When compiling I get this warning:
thrust\detail\allocator\allocator_traits.inl(251): warning C4700: uninitialized local variable 'result' used

When running in debug mode I get this runtime error in allocator_traits.inl(251):
Run-Time Check Failure #3 - The variable 'result' is being used without being initialized.

I fixed by changing line 250 from:
`typename allocator_system<Alloc>::type result;`
to
`typename allocator_system<Alloc>::type result {};`

**Comment by allisonvacanti** [comment]
This was fixed by #1009.
