### ISSUE TITLE
Project doesn't install headers

### ISSUE THREAD

**Issue by yurivict** [thrust/thrust#1210]
1.9.5 installed the headers, and 1.9.10-21 - doesn't.

**Comment by allisonvacanti** [comment]
Indeed it did: https://github.com/thrust/thrust/blob/aded199441e022f7fb89d51c1b2804ebc448c1af/CMakeLists.txt

Apparently the install logic got removed at some point. We should add this back.

**Comment by allisonvacanti** [comment]
I'll add this to my list of CMake features to add, but it might be a little bit before I can get to it.

As a workaround for now, just copying the `thrust/thrust` directory into the install location should provide a usable version of thrust.

**Comment by allisonvacanti** [comment]
Rules have been added in #1245.
