### ISSUE TITLE
Divergent use of `<thrust/detail/memory_wrapper.h>` in some headers between Git and Perforce

### ISSUE THREAD

**Issue by brycelelbach** [thrust/thrust#1236]
These headers do not use `<thrust/detail/memory_wrapper.h>`. Should they?

There is divergence between Perforce and Git here. In Perforce, they use them.

Please resolve ASAP. If the resolution is that they shouldn't be used, then the change will need to be made manually in Perforce.

https://github.com/thrust/thrust/blob/main/thrust/allocate_unique.h#L19

https://github.com/thrust/thrust/blob/main/thrust/detail/allocator/allocator_traits.inl#L26

It would also be good to figure out how we ended up here

**Comment by dkolsen-pgi** [comment]
Those files were changed to include `<thrust/detail/memory_wrapper.h>` instead of `<memory>` in #1228, which was merged into master (and pushed to staging/1.9.10-1) six days ago.  But that commit was somehow undone in git.  I don't know how the git repository was reverted.

**Comment by dkolsen-pgi** [comment]
I redid the change, and created PR #1238

**Comment by allisonvacanti** [comment]
Leaving open until we can validate that nothing else was lost.
