### ISSUE TITLE
Compilation fails when including complex.h

### ISSUE THREAD

**Issue by wkjung** [thrust/thrust#1244]
Hi.

With nvcc V11.0.194 (g++ -v outputs (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0), I tried to compile the code below:
**a.cu**
```cpp
#include <complex.h>
#include <thrust/copy.h>
```
But I got these errors:
```bash
~/thrust/thrust/iterator/constant_iterator.h(220): error #40: expected an identifier
~/thrust/thrust/iterator/constant_iterator.h(222): error #79: expected a type specifier
~/thrust/thrust/iterator/constant_iterator.h(222): error #79: expected a type specifier
```
Is it a bug or intended behavior? Thanks.

**Comment by allisonvacanti** [comment]
That's troubling.

It does seem to compile if the headers are reversed as a work around:

```
$ cat a.cu
#include <thrust/copy.h>
#include <complex.h>

$ nvcc -c tt.cu; echo $?
0
```

**Comment by dkolsen-pgi** [comment]
`<complex.h>` defines a macro named `I`, which represents the unit imaginary number.  That clashes with any uses of the identifier `I` in any code after the include of `<complex.h>`.  It would be good if Thrust were changed to not use the identifier `I` anywhere.  There are not a lot, and the change should be simple, but there are several files in addition to `<thrust/iterator/constant_iterator.h>`.

**Comment by allisonvacanti** [comment]
Thanks for the explanation, @dkolsen-pgi, I'm surprised I've never encountered that before.

We should fix this at some point.
