### ISSUE TITLE
missing #include <stdexcept> in thrust/detail/contiguous_storage.h

### ISSUE THREAD

**Issue by hpcdgrie** [thrust/thrust#1262]
This does not compile with MSVC 14

**Comment by allisonvacanti** [comment]
I'll add the header, but heads up that MSVC 2015 is deprecated and likely to stop working with Thrust `main` soon. The version of Thrust that ships with the CUDA TK will continue to support MSVC2015 with deprecation warnings for now, but support will be dropped completely at some point.

Current MSVC support is limited to 2017 and 2019.

**Comment by hpcdgrie** [comment]
Ok, thank your. Sorry for the confusion with the MSVC version. I meant the version that ships with Visual Studio 2019 and as far as I know that is MSVC 14.X.

**Comment by hpcdgrie** [comment]
And I made a mistake: it ist the contiguous_storage.inl file that misses the #include <stdexcept> for the use of std::runtime_error, not the header.

**Comment by allisonvacanti** [comment]
No worries, the [MSVC toolchain versioning is weird and nonsensical](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering). 14 could refer to:

- MSVC 2005 (`_MSC_VER == 1400`)
- MSVC 2015 (VS 14.0)
- MSVC 2015/2017/2019 (MSVC++ 14.x)

So much fun.

**Comment by allisonvacanti** [comment]
Fixed in #1265.
