### ISSUE TITLE
option to prefer compilation speed over performance?

### ISSUE THREAD

**Issue by andrewcorrigan** [thrust/thrust#469]
My Thrust-based code takes 1-2 minutes to compile with modern GCC or LLVM using the serial-CPU backend.  Compiling the exact same code, only with the CUDA backend, can take 20+ minutes to compile, even with the latest CUDA 6 RC.  This is an enormous hindrance to development.  I imagine that the problem primarily lies with NVCC, and I have hoped that the situation would improve on its own, but especially with this latest CUDA release I have lost hope that NVCC's performance will ever improve.

Is there anything that can be done in Thrust to improve compile speeds?      Would it be possible to implement something like THRUST_FAST_COMPILE, to statically choose algorithms that would still function correctly, but don't take so long to compile?

**Comment by andrewcorrigan** [comment]
My Thrust-based code compiles quickly now with Clang, instead of NVCC.

**Comment by egaburov** [comment]
If it is not too much to ask can you please post here compilation time with clang and with nvcc 8.0 which was released recently. Otherwise, if it is open source, please  point me to the source where I can do this sort of benchmark myself. thank you.

**Comment by andrewcorrigan** [comment]
For one configuration the difference is approximately 5 minutes with clang, vs over an hour with nvcc 8.0.   This is for the current, C++11 version of my code, which makes use of my variadic-tuple branch of Thrust.
