### ISSUE TITLE
update cuda::arch constants and calculator

### ISSUE THREAD

**Issue by jaredhoberock** [thrust/thrust#50]
See Section 4.2 of the CUDA Programming Guide [1] and the new CUDA Occupancy Calculator [2]

[1] http://developer.download.nvidia.com/compute/DevZone/docs/html/C/doc/CUDA_C_Programming_Guide.pdf
[2] http://developer.download.nvidia.com/compute/DevZone/docs/html/C/tools/CUDA_Occupancy_Calculator.xls

I think we might be able to remove the occupancy calculator entirely and make decisions based on cudaFuncAttributes::maxThreadsPerBlock instead.

Forwarded from http://code.google.com/p/thrust/issues/detail?id=382

**Comment by brycelelbach** [comment]
Related to nvbug 1468459, which is an RFE for Thrust to use the new occupancy API and remove the old calculator.

**Comment by brycelelbach** [comment]
1468459 is closed; I have confirmed that Thrust uses the CUDA occupancy APIs now.
