### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by umokk** [thrust/thrust#552]
Commit 140e7c13f26887bf42cf13cfb1bc17986db685be causes a compilation error:
thrust/detail/function.h(60): error C2668: 'thrust::raw_reference_cast' : ambiguous call to overloaded function
          thrust/detail/raw_reference_cast.inl(266): could be 'thrust::detail::tuple_of_iterator_references<int &,int &,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type> thrust::raw_reference_castthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type>(thrust::detail::tuple_of_iterator_referencesthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type>)'
          with
          [
              T=int
          ]
          thrust/detail/raw_reference_cast.h(102): or       'thrust::detail::tuple_of_iterator_references<int &,int &,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type> thrust::raw_reference_castthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type>(thrust::detail::tuple_of_iterator_referencesthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type>)'
          with
          [
              T=int
          ]
          thrust/detail/raw_reference_cast.h(96): or       'const thrust::detail::tuple_of_iterator_referencesthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type> &thrust::raw_reference_cast<Argument>(const thrust::detail::tuple_of_iterator_referencesthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type> &)'
          with
          [
              T=int
  ,            Argument=thrust::detail::tuple_of_iterator_referencesthrust::device_reference<int,thrust::device_reference<int>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type>
          ]
          thrust/detail/raw_reference_cast.h(89): or       'const thrust::detail::tuple_of_iterator_referencesthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type> &thrust::raw_reference_cast<const Argument>(const thrust::detail::tuple_of_iterator_referencesthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type> &)'
          with
          [
              T=int
  ,            Argument=thrust::detail::tuple_of_iterator_referencesthrust::device_reference<int,thrust::device_reference<int>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type>
          ]
          while trying to match the argument list '(const thrust::detail::tuple_of_iterator_referencesthrust::device_reference<T,thrust::device_reference<T>,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type,thrust::null_type>)'
          with
          [
              T=int
          ]

**Comment by brycelelbach** [comment]
Reopen if this is still an issue.
