### ISSUE TITLE
New warnings with MSVC 2013

### ISSUE THREAD

**Issue by jaredhoberock** [thrust/thrust#568]
Reported here: https://groups.google.com/d/msg/thrust-users/LP7oCf0yBvQ/yxgbt08Qpo4J

Hi

I just shifted from VC++2012 to VC++2013. I have warning level 4 turned on for my builds. I am using thrust 1.70 radix sorting primitives with host CPP backend. 

> # define THRUST_HOST_SYSTEM THRUST_HOST_SYSTEM_CPP
> # define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_CPP
> # include "thrust/sort.h"
> # include "thrust/system/cpp/execution_policy.h"
> 
> thrust::stable_sort_by_key( thrust::cpp::par,....)

Now when I compile my code I get following warnings. I would like to know if these warnings can be safely ignored. If not, how to get rid of them ?

1>E:\github\src\thrust/iterator/detail/iterator_category_to_traversal.h(40): warning C4515: 'detail' : namespace uses itself
1>E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(48): warning C4127: conditional expression is constant
1>E:\github\src\thrust/system/detail/internal/scalar/sort.inl(72): warning C4127: conditional expression is constant
1>          E:\github\src\thrust/system/detail/internal/scalar/sort.inl(153) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::sort_detail::stable_sort_by_key<RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering>(RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering,thrust::detail::true_type)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            StrictWeakOrdering=thrust::less<value_type>
1>          ]
1>          E:\github\src\thrust/system/cpp/detail/sort.h(53) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::stable_sort_by_key<RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering>(RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            StrictWeakOrdering=thrust::less<value_type>
1>          ]
1>          E:\github\src\thrust/detail/sort.inl(131) : see reference to function template instantiation 'void thrust::system::cpp::detail::stable_sort_by_keythrust::system::cpp::detail::par_t,RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering(thrust::system::cpp::detail::execution_policythrust::system::cpp::detail::par_t &,RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            StrictWeakOrdering=thrust::less<value_type>
1>          ]
1>          E:\github\src\thrust/system/detail/generic/sort.inl(113) : see reference to function template instantiation 'void thrust::stable_sort_by_key<DerivedPolicy,RandomAccessIterator1,RandomAccessIterator2,thrust::less<value_type>>(const thrust::detail::execution_policy_base<DerivedPolicy> &,RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering)' being compiled
1>          with
1>          [
1>              DerivedPolicy=thrust::system::cpp::detail::par_t
1>  ,            RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            StrictWeakOrdering=thrust::less<value_type>
1>          ]
1>          E:\github\src\thrust/detail/sort.inl(116) : see reference to function template instantiation 'void thrust::system::detail::generic::stable_sort_by_key<Derived,RandomAccessIterator1,RandomAccessIterator2>(thrust::execution_policy<Derived> &,RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2)' being compiled
1>          with
1>          [
1>              Derived=thrust::system::cpp::detail::par_t
1>  ,            RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>          ]
1>          E:\github\src\MortonSfc.cpp(204) : see reference to function template instantiation 'void thrust::stable_sort_by_key<DerivedPolicy,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>>(const thrust::detail::execution_policy_base<DerivedPolicy> &,RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2)' being compiled
1>          with
1>          [
1>              DerivedPolicy=thrust::system::cpp::detail::par_t
1>  ,            RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>          ]
1>E:\github\src\thrust/system/detail/internal/scalar/sort.inl(80): warning C4127: conditional expression is constant
1>E:\github\src\thrust/system/detail/internal/scalar/sort.inl(64): warning C4100: 'comp' : unreferenced formal parameter
1>E:\github\src\thrust/detail/allocator/temporary_allocator.h(68): warning C4512: 'thrust::detail::temporary_allocator<T,System>' : assignment operator could not be generated
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/allocator/no_throw_allocator.h(28) : see reference to class template instantiation 'thrust::detail::temporary_allocator<T,System>' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.h(124) : see reference to class template instantiation 'thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<T,System>' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.h(39) : see reference to class template instantiation 'thrust::detail::allocator_traits<Alloc>' being compiled
1>          with
1>          [
1>              Alloc=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>          ]
1>          E:\github\src\thrust/detail/temporary_array.h(45) : see reference to class template instantiation 'thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(423) : see reference to class template instantiation 'thrust::detail::temporary_array<KeyType,ExecutionPolicy>' being compiled
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_primitive_sort.inl(113) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::stable_radix_sort_by_key<RandomAccessIterator1,RandomAccessIterator2>(RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_primitive_sort.inl(132) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::stable_primitive_sort_detail::stable_primitive_sort_by_key<RandomAccessIterator1,RandomAccessIterator2>(RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/sort.inl(78) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::stable_primitive_sort_by_key<RandomAccessIterator1,RandomAccessIterator2>(RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/sort.inl(153) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::sort_detail::stable_sort_by_key<RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering>(RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2,StrictWeakOrdering,thrust::detail::true_type)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            StrictWeakOrdering=thrust::less<value_type>
1>          ]
1>E:\github\src\thrust/detail/allocator/no_throw_allocator.h(57): warning C4512: 'thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<T,System>' : assignment operator could not be generated
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>E:\github\src\thrust/detail/allocator/temporary_allocator.h(68): warning C4512: 'thrust::detail::temporary_allocator<T,System>' : assignment operator could not be generated
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/allocator/no_throw_allocator.h(28) : see reference to class template instantiation 'thrust::detail::temporary_allocator<T,System>' being compiled
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.h(124) : see reference to class template instantiation 'thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<T,System>' being compiled
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.h(39) : see reference to class template instantiation 'thrust::detail::allocator_traits<Alloc>' being compiled
1>          with
1>          [
1>              Alloc=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>          ]
1>          E:\github\src\thrust/detail/temporary_array.h(45) : see reference to class template instantiation 'thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>' being compiled
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(424) : see reference to class template instantiation 'thrust::detail::temporary_array<ValueType,ExecutionPolicy>' being compiled
1>E:\github\src\thrust/detail/allocator/no_throw_allocator.h(57): warning C4512: 'thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<T,System>' : assignment operator could not be generated
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>E:\github\src\thrust/detail/allocator/allocator_traits.inl(122): warning C4512: 'thrust::detail::allocator_traits_detail::has_member_destroy_impl_has_member<T,Signature>::base' : assignment operator could not be generated
1>          with
1>          [
1>              T=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>  ,            Signature=void (unsigned __int64 _)
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.inl(122) : see declaration of 'thrust::detail::allocator_traits_detail::has_member_destroy_impl_has_member<T,Signature>::base'
1>          with
1>          [
1>              T=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>  ,            Signature=void (unsigned __int64 *)
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.inl(122) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_destroy_impl_has_member<T,Signature>::base' being compiled
1>          with
1>          [
1>              T=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>  ,            Signature=void (unsigned __int64 *)
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.inl(122) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_destroy_impl_has_member<T,Signature>' being compiled
1>          with
1>          [
1>              T=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>  ,            Signature=void (unsigned __int64 *)
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.inl(127) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_destroy_impl<Alloc,void (T *)>' being compiled
1>          with
1>          [
1>              Alloc=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>  ,            T=unsigned __int64
1>          ]
1>          E:\github\src\thrust/detail/allocator/destroy_range.inl(41) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_destroy<Allocator,T>' being compiled
1>          with
1>          [
1>              Allocator=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>  ,            T=unsigned __int64
1>          ]
1>          E:\github\src\thrust/detail/allocator/destroy_range.inl(81) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_effectful_member_destroy<Allocator,unsigned __int64>' being compiled
1>          with
1>          [
1>              Allocator=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>          ]
1>          E:\github\src\thrust/detail/allocator/destroy_range.inl(152) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::enable_if_destroy_range_case3<Allocator,Pointer>' being compiled
1>          with
1>          [
1>              Allocator=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>  ,            Pointer=thrust::pointer<KeyType,ExecutionPolicy,thrust::use_default,thrust::use_default>
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(233) : see reference to function template instantiation 'void thrust::detail::destroy_rangethrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>,Base,__int64>(Allocator &,Pointer,Size)' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>  ,            Base=thrust::pointer<KeyType,ExecutionPolicy,thrust::use_default,thrust::use_default>
1>  ,            Allocator=thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<KeyType,ExecutionPolicy>
1>  ,            Pointer=thrust::pointer<KeyType,ExecutionPolicy,thrust::use_default,thrust::use_default>
1>  ,            Size=__int64
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(232) : while compiling class template member function 'void thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::destroy(thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>,thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>)'
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/temporary_array.inl(142) : see reference to function template instantiation 'void thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::destroy(thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>,thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>)' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(81) : while compiling class template member function 'thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default> thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::begin(void)'
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(426) : see reference to function template instantiation 'thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default> thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::begin(void)' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/temporary_array.h(45) : see reference to class template instantiation 'thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(423) : see reference to class template instantiation 'thrust::detail::temporary_array<KeyType,ExecutionPolicy>' being compiled
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_primitive_sort.inl(113) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::stable_radix_sort_by_key<RandomAccessIterator1,RandomAccessIterator2>(RandomAccessIterator1,RandomAccessIterator1,RandomAccessIterator2)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>          ]
1>E:\github\src\thrust/detail/allocator/allocator_traits.inl(122): warning C4512: 'thrust::detail::allocator_traits_detail::has_member_destroy_impl_has_member<T,Signature>::base' : assignment operator could not be generated
1>          with
1>          [
1>              T=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>  ,            Signature=void (Charge *_)
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.inl(122) : see declaration of 'thrust::detail::allocator_traits_detail::has_member_destroy_impl_has_member<T,Signature>::base'
1>          with
1>          [
1>              T=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>  ,            Signature=void (Charge *_)
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.inl(122) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_destroy_impl_has_member<T,Signature>::base' being compiled
1>          with
1>          [
1>              T=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>  ,            Signature=void (Charge *_)
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.inl(122) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_destroy_impl_has_member<T,Signature>' being compiled
1>          with
1>          [
1>              T=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>  ,            Signature=void (Charge **)
1>          ]
1>          E:\github\src\thrust/detail/allocator/allocator_traits.inl(127) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_destroy_impl<Alloc,void (T *)>' being compiled
1>          with
1>          [
1>              Alloc=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>  ,            T=Charge *
1>          ]
1>          E:\github\src\thrust/detail/allocator/destroy_range.inl(41) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_destroy<Allocator,T>' being compiled
1>          with
1>          [
1>              Allocator=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>  ,            T=Charge *
1>          ]
1>          E:\github\src\thrust/detail/allocator/destroy_range.inl(81) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_effectful_member_destroy<Allocator,Charge *>' being compiled
1>          with
1>          [
1>              Allocator=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>          ]
1>          E:\github\src\thrust/detail/allocator/destroy_range.inl(152) : see reference to class template instantiation 'thrust::detail::allocator_traits_detail::enable_if_destroy_range_case3<Allocator,Pointer>' being compiled
1>          with
1>          [
1>              Allocator=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>  ,            Pointer=thrust::pointer<ValueType ,ExecutionPolicy,thrust::use_default,thrust::use_default>
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(233) : see reference to function template instantiation 'void thrust::detail::destroy_rangethrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>,Base,__int64>(Allocator &,Pointer,Size)' being compiled
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>  ,            Base=thrust::pointer<ValueType ,ExecutionPolicy,thrust::use_default,thrust::use_default>
1>  ,            Allocator=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<ValueType ,ExecutionPolicy>>
1>  ,            Pointer=thrust::pointer<ValueType ,ExecutionPolicy,thrust::use_default,thrust::use_default>
1>  ,            Size=__int64
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(232) : while compiling class template member function 'void thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::destroy(thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>,thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>)'
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/temporary_array.inl(142) : see reference to function template instantiation 'void thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::destroy(thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>,thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>)' being compiled
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(81) : while compiling class template member function 'thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default> thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::begin(void)'
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(426) : see reference to function template instantiation 'thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default> thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::begin(void)' being compiled
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/temporary_array.h(45) : see reference to class template instantiation 'thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>' being compiled
1>          with
1>          [
1>              T=ValueType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(424) : see reference to class template instantiation 'thrust::detail::temporary_array<ValueType,ExecutionPolicy>' being compiled
1>E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(212): warning C4127: conditional expression is constant
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(348) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::detail::radix_sort<8,true,RandomAccessIterator1,RandomAccessIterator2,RandomAccessIterator3,RandomAccessIterator4>(RandomAccessIterator1,RandomAccessIterator2,RandomAccessIterator3,RandomAccessIterator4,const size_t)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=thrust::detail::normal_iteratorthrust::pointer<KeyType,ExecutionPolicy,thrust::use_default,thrust::use_default>
1>  ,            RandomAccessIterator3=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            RandomAccessIterator4=thrust::detail::normal_iterator<thrust::pointer<ValueType ,ExecutionPolicy,thrust::use_default,thrust::use_default>>
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(375) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::detail::radix_sort_dispatcher<0x08>::operator ()<RandomAccessIterator1,RandomAccessIterator2,RandomAccessIterator3,RandomAccessIterator4>(RandomAccessIterator1,RandomAccessIterator2,RandomAccessIterator3,RandomAccessIterator4,const size_t)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            RandomAccessIterator2=thrust::detail::normal_iteratorthrust::pointer<KeyType,ExecutionPolicy,thrust::use_default,thrust::use_default>
1>  ,            RandomAccessIterator3=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            RandomAccessIterator4=thrust::detail::normal_iterator<thrust::pointer<ValueType ,ExecutionPolicy,thrust::use_default,thrust::use_default>>
1>          ]
1>          E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(426) : see reference to function template instantiation 'void thrust::system::detail::internal::scalar::detail::radix_sort<RandomAccessIterator1,thrust::detail::normal_iterator<thrust::pointer<T,System,thrust::use_default,thrust::use_default>>,RandomAccessIterator2,thrust::detail::normal_iteratorthrust::pointer<Charge,System,thrust::use_default,thrust::use_default>>(RandomAccessIterator1,thrust::detail::normal_iteratorthrust::pointer<T,System,thrust::use_default,thrust::use_default>,RandomAccessIterator3,RandomAccessIterator4,const size_t)' being compiled
1>          with
1>          [
1>              RandomAccessIterator1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>
1>  ,            T=KeyType
1>  ,            System=ExecutionPolicy
1>  ,            RandomAccessIterator2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            RandomAccessIterator3=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<Charge *>>>
1>  ,            RandomAccessIterator4=thrust::detail::normal_iterator<thrust::pointer<ValueType ,ExecutionPolicy,thrust::use_default,thrust::use_default>>
1>          ]
1>E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(241): warning C4127: conditional expression is constant
1>E:\github\src\thrust/system/detail/internal/scalar/stable_radix_sort.inl(263): warning C4127: conditional expression is constant
1>E:\github\src\thrust/detail/allocator/temporary_allocator.inl(51): warning C4100: 'n' : unreferenced formal parameter
1>          E:\github\src\thrust/detail/allocator/temporary_allocator.inl(52) : while compiling class template member function 'void thrust::detail::temporary_allocator<T,System>::deallocate(thrust::pointer<T,System,thrust::use_default,thrust::use_default>,thrust::detail::temporary_allocator<T,System>::size_type)'
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/allocator/no_throw_allocator.h(47) : see reference to function template instantiation 'void thrust::detail::temporary_allocator<T,System>::deallocate(thrust::pointer<T,System,thrust::use_default,thrust::use_default>,thrust::detail::temporary_allocator<T,System>::size_type)' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(136) : while compiling class template member function 'void thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::allocate(unsigned __int64)'
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(51) : see reference to function template instantiation 'void thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::allocate(unsigned __int64)' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/contiguous_storage.inl(47) : while compiling class template member function 'thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::contiguous_storage(unsigned __int64,const thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<T,System> &)'
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]
1>          E:\github\src\thrust/detail/temporary_array.inl(64) : see reference to function template instantiation 'thrust::detail::contiguous_storage<T,thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<T,System>>>::contiguous_storage(unsigned __int64,const thrust::detail::no_throw_allocatorthrust::detail::temporary_allocator<T,System> &)' being compiled
1>          with
1>          [
1>              T=KeyType
1>  ,            System=ExecutionPolicy
1>          ]

Thanks

**Comment by brycelelbach** [comment]
Closing, because this is ancient and warnings.
