### ISSUE TITLE
API Bindings Request: Dart

### ISSUE THREAD

**Issue by knownasilya** [thrust/thrust#585]
Would love to see Dart bindings for Thrust, with the option of using Dartium instead of Chromium.

**Comment by dachziegel** [comment]
I guess you chose the wrong 'thrust', was your request meant for https://github.com/breach/thrust ?

**Comment by jaredhoberock** [comment]
OK, this issue makes more sense to me now. I think it's safe to say it was meant for the other similarly-named project.
