### ISSUE TITLE
slow compilation with CUDA 6.5

### ISSUE THREAD

**Issue by dachziegel** [thrust/thrust#641]
I just switched from CUDA 6 to CUDA 6.5 and noticed that compilation of my thrust based code is slowed down **a lot**.

Because my own, more complex code did not yet finish compiling I created a simple demo program:

https://gist.github.com/dachziegel/c7bc0226fe2f16196f3e

When I use the thrust version which is delivered with CUDA 6.5 this takes around 6 seconds:

```
$ time nvcc -arch sm_30 compile_time.cu

real    0m6.469s
user    0m6.010s
sys 0m0.452s
```

When I use the thrust development version from github it takes around 30 (!) seconds:

```
$time nvcc -arch sm_30 -I/tmp/thrust-github/ compile_time.cu

real    0m31.051s
user    0m30.237s
sys 0m0.782s
```

The difference is even higher if the program is a bit more complex, e.g. this one from another bug report: https://gist.github.com/dachziegel/11288269

when using CUDA 6.5:
thrust from CUDA 6.5 takes around **7 seconds**, thrust development version from github took **7.44 minutes**(!).

when using CUDA 6:
thrust development version from github takes **51 seconds**.

when using CUDA 7:
thrust development version from github takes **41 seconds**.

My system is a 64bit Ubuntu 14.04.

**Comment by jaredhoberock** [comment]
On my system, nvcc 7 takes 60 seconds on your second program:

$ time nvcc -arch=sm_30 -I. test.cu 

real	1m0.170s
user	0m52.412s
sys	0m1.363s

Could you try with CUDA 7 on your system?

**Comment by dachziegel** [comment]
I already added the time for CUDA 7 above (41 seconds).

**Comment by jaredhoberock** [comment]
Thanks. I have filed an issue against the compiler.
