### ISSUE TITLE
Possible error in the documentation about Asynchronous calls using thrust::system::cuda::par

### ISSUE THREAD

**Issue by gnthibault** [thrust/thrust#660]
Dear Thrust developers, first I would like to thank you for all the incredible work you do for the cuda community.

I am on the way to delete part of my own cuda buffers wrapper in order to use your fantastic tools.
I decided to do so after seeing that you implemented a way to use concurrents stream through execution_policy.

Unfortunately, at the beginning my code was not able to compile because I used the documentation here:
https://thrust.github.io/doc/group__execution__policies.html#ga64da56b76f487725a99818cd63662dac

Where you use:

 // create two CUDA streams
  cudaStream_t s1, s2;
  cudaStreamCreate(&s1);
  cudaStreamCreate(&s2);
  thrust::counting_iterator<int> iter(0);
  // execute for_each on two different streams
  thrust::for_each(thrust::cuda::par(s1), iter, iter + 1, printf_functor(s1));
  thrust::for_each(thrust::cuda::par(s2), iter, iter + 1, printf_functor(s2));

I think that thrust::cuda::par.on(s1) would be preferable because the previous example do not compile on my cuda-7.0 toolkit, when placed in .cu files.

Thank you for your work again.

**Comment by jaredhoberock** [comment]
Thanks for reporting the issue Thibaut. The typo has been corrected in the source code and the online documentation will be refreshed on the next release.
