### ISSUE TITLE
thrust::host_malloc

### ISSUE THREAD

**Issue by ludvi025** [thrust/thrust#666]
This might already exist, but I wanted to use a consistent pattern for allocating memory on both the host and device. I like `thrust::device_malloc<T>(size)` and wanted something equivalent for host, instead of doing `malloc(sizeof(T) * size)`. Consider including this code snippet:

```
template <typename T>
T* host_malloc(int size) {
  return (T*) malloc(sizeof(T) * size);
}
```

**Comment by jaredhoberock** [comment]
thrust::malloc exists: https://thrust.github.io/doc/group__allocation__functions.html#ga6371d262cf49b52d38812d4b30b037dc
