### ISSUE TITLE
Extremely slow sorting operation over float when using THRUST_DEVICE_SYSTEM_OMP

### ISSUE THREAD

**Issue by gnthibault** [thrust/thrust#667]
Hi all,
As I already mentioned in an other post, I thank you for all the work you have done in thrust, you made a fantastic job.
Thrust is so usefull that, as we are organizing an introduction tutorial for beginner in my university, I will be in charge of designing the thrust tutorial.

Doing so, I tried to show various aspects of Thrust, and among other its "versatility", that allows to change device backend at compile time.
You can find the example I made in the following small project:

https://github.com/gnthibault/Cuda_Thrust_Introduction
In the folder DeviceBackend I wrote the following code:

int main( int argc, char* argv[] )
{
	const size_t sizeVect = 1024*1024*128; //I dont know why forum doesn't show 1024x1024x128

	//Declare and allocate memory for device vector
	thrust::device_vector<float> deviceVector(sizeVect);

	//Ordered sequence used for random number generation
	thrust::counting_iterator<size_t> index_sequence_begin(0);

	//Generation of the random list of float
	thrust::transform(	index_sequence_begin,
						index_sequence_begin + sizeVect,
						deviceVector.begin(),
						normalRandomFunctor(0.f,10.f) );

	//Now measure how many time it take to perform sorting operation
	auto begin = std::chrono::high_resolution_clock::now();

	thrust::sort( deviceVector.begin(), deviceVector.end() );

	#if THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA
		cudaDeviceSynchronize(); //Synchronize because of aynchronous behaviour in cuda mode
	#endif // THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA

	auto end = std::chrono::high_resolution_clock::now();
	std::chrono::duration<float> _elapsed = end - begin;
	double elapsed = _elapsed.count();
	double throughput = (sizeVect/1.e6)/elapsed;

	#if THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA
		std::cout << "Cuda backend sorted " ;
	#elif THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_OMP
		std::cout << "OpenMP backend sorted " ;
	#elif THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_TBB
		std::cout << "TBB backend sorted " ;
	#endif // THRUST_DEVICE_SYSTEM == THRUST_DEVICE_SYSTEM_CUDA

	std::cout << sizeVect << " elements in " << elapsed << " seconds ("<< throughput <<" Millions of elements/s )"<< std::endl;

	return EXIT_SUCCESS;
}

And here are the results I got:

      -Cuda backend sorted 134217728 elements in 0.485675 seconds (276.353 Millions of elements/s )

      -OpenMP backend sorted 134217728 elements in 224.313 seconds (0.598351 Millions of elements/s )

      -TBB backend sorted 134217728 elements in 126.267 seconds (1.06297 Millions of elements/s )

Using the following configuration:
Cuda device: Gtx Titan 
CPU: intel Core i73820 (4core with HT)
Compiler: gcc 4.8.2, using -std=c++11 option
TBB version: 4.2
Distribution: centOS 6 distribution with kernel 3.12.8-1
Cuda version: 7.0.28 with original thrust template library

I feel like those results doesn't reflect Thrust ability to use host parallel backend as good as device one, am I wrong, or is there something wrong in my code ?

Thank you in advance

PS: I may also post this question on stackoverflow.

**Comment by jaredhoberock** [comment]
Here are the results I get from your program on my workstation:

$ nvcc -std=c++11 -O3 test.cu -run -arch=sm_35
-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA
Cuda backend sorted 134217728 elements in 0.507154 seconds (264.649
Millions of elements/s )

$ nvcc -std=c++11 -O3 test.cu -run -arch=sm_35
-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_OMP -Xcompiler -fopenmp
OpenMP backend sorted 134217728 elements in 3.78381 seconds (35.4716
Millions of elements/s )

$ nvcc -std=c++11 -O3 test.cu -run -arch=sm_35
-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_TBB -ltbb
TBB backend sorted 134217728 elements in 2.09192 seconds (64.16 Millions of
elements/s )

$ nvcc --version ; echo ; g++ --version ; cat /etc/lsb-release ; echo ; cat
/proc/driver/nvidia/gpus/0000\:02\:00.0/information
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27

g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

Model:  Tesla K20c
IRQ:    48
GPU UUID:  GPU-e8818222-5966-5f99-35cf-decf38d578a3
Video BIOS:  80.10.14.00.02
Bus Type:  PCIe
DMA Size:  40 bits
DMA Mask:  0xffffffffff
Bus Location:  0000:02:00.0

Maybe you're not compiling with optimization enabled?

**Comment by gnthibault** [comment]
Thank you very much for your help, and sorry for my silly question ...

I added the following flag to nvcc: "-O3" and I get pleasing results on CPU:

OpenMP backend sorted 134217728 elements in 2.01271 seconds (66.685 Millions of elements/s )
TBB backend sorted 134217728 elements in 1.42055 seconds (94.4827 Millions of elements/s )

TBB backend appear to be surprisingly faster at this exercise +1: 

Thank you again for your help and sorry for posting in the development forum a question about a non directly related topic.
