### ISSUE TITLE
When omitting __device__, for_each on a device_vector silently fails without warning or error

### ISSUE THREAD

**Issue by dachziegel** [thrust/thrust#668]
I just forgot to add the `__device__` specifier to a custom functor. I did get no compiler warnings, but at runtime, the call to `thrust::for_each`  for a `thrust::device_vector` was not executed and failed silently.
I created a simple example to demonstrate this issue:

**silent.cu**

```
#include <iostream>
#include <thrust/device_vector.h>  
#include <thrust/for_each.h>
#include <thrust/copy.h>

#ifdef USE_SPECIFIER
#define SPECIFIER __device__
#else
#define SPECIFIER
#endif

struct Fun
{
    template <typename T>
    SPECIFIER
    void operator()(T& t)
    {
        printf("hello from Fun\n");
        t = 1;
    }
};

int main()
{
    const int size = 10;
    thrust::device_vector<int> v1(size);
    thrust::for_each(
        v1.begin(),
        v1.end(),
        Fun()
    );
    thrust::copy(v1.begin(), v1.end(), std::ostream_iterator<int>(std::cout, "\t"));
    std::cout << std::endl;
}
```

When compiling and running without the `__device__` specifier:
`nvcc silent.cu -o silent && ./silent`

I get the following output:
`0    0   0   0   0   0   0   0   0   0`

When compiling and running with the `__device__` specifier:
`nvcc silent.cu -DUSE_SPECIFIER -o silent && ./silent`

I get the expected output:

```
1   1   1   1   1   1   1   1   1   1   
hello from Fun
hello from Fun
hello from Fun
hello from Fun
hello from Fun
hello from Fun
hello from Fun
hello from Fun
hello from Fun
hello from Fun
```

I am using CUDA 7 on Linux.

**Comment by zeryx** [comment]
I don't believe this would be an error, as a host functor does not explicitly require the __host__ specifier.
This seems to be a CUDA related issue rather than Thrust specifically, as the specifiers are not required in .cu files for most objects (including functors), if you feel like the specifiers should be explicitly defined for functors I think it would need to be taken up on the CUDA developers [site][cuda].

[cuda]: https://devtalk.nvidia.com/default/board/57/cuda-programming-and-performance/

**Comment by dachziegel** [comment]
You might be right, however a runtime error (at least in debug mode) would be nice to receive. As I wrote above, you do not get anything which indicates that your functor did not succeed.

**Comment by jaredhoberock** [comment]
It's unfortunate that there is no warning or error issued, but I'm not sure there is anything that Thrust can do for this case. All of Thrust's algorithms are `__host__ __device__` functions and the user functions and functors it invokes may be either `__host__`, `__device__`, or `__host__ __device__`. Many of the algorithm implementations need to be able to invoke any of the three kinds of functions.

The only way to achieve this is by invoking these user functions from `__host__ __device__` functions and silencing the warning or error issued when the user function isn't annotated `__host__ __device__`.

Most of the time, this policy works out when the user annotates his functor correctly and invokes the algorithm in a way that matches the annotation. But when the user forgets to annotate the functor, it will silently fail.

I do not know of any practical means of implementing a runtime error that could communicate to the user what caused the problem, even in debug mode.

**Comment by dachziegel** [comment]
Does Thrust use the type of the iterator to infer whether this will happen on the host or the device?

In my above example, I pass `thrust::device_vector<int>::iterator` to `thrust::for_each`, so maybe that  that knowledge could be used to ensure that the functor is a `__device__` one?

**Comment by jaredhoberock** [comment]
Thrust uses the (possibly implicit) execution policy to decide where to execute the algorithm.

Anyway, Thrust has no way to ensure that a functor is annotated in a particular way, because CUDA annotations cannot be introspected.

**Comment by zeryx** [comment]
@jaredhoberock what about allowing custom functors to use a thrust specific decorator, which encapsulates the __device__ __host__ decoratiors and is able to throw errors in the event that one of those arguments is missing from the functor declaration?

It would certainly remove an element of confusion for new users, as I had the exact same problem that @dachziegel when I first started playing with thrust.

**Comment by jaredhoberock** [comment]
Real soon now folks will want to just use lambdas, not functions or functors.

Anyway thanks for the suggestions. You might consider taking your case to the CUDA compiler folks to change or improve the way the annotations get checked :-) I think this is a problem to be solved by a compiler, not a library.
