### ISSUE TITLE
Add "Developer Information" to wiki

### ISSUE THREAD

**Issue by dachziegel** [thrust/thrust#672]
At the old google code project, there was a [DeveloperInformation](https://code.google.com/p/thrust/wiki/DeveloperInfo) page in the wiki, which is outdated.

I created a new and updated wiki page at

https://github.com/dachziegel/thrust/wiki/Developer-Information

which is based on the old wiki page.

Can this page be included in the official wiki?

**Comment by jaredhoberock** [comment]
Sure, is there a way to submit a new wiki page through a pull request?

**Comment by dachziegel** [comment]
Not directly, but we could use the workflow described here: http://stackoverflow.com/a/11481887/678093

**Comment by jaredhoberock** [comment]
I just added it directly, copying the markdown from your page.

**Comment by dachziegel** [comment]
great!
