### ISSUE TITLE
implement thrust::unique using thrust::transform_iterator

### ISSUE THREAD

**Issue by dachziegel** [thrust/thrust#677]
`thrust::unique` could be implemented using `thrust::transform_iterator`.
This avoids having to allocate temporary memory for the stencil and results in higher performance.

I implemented `thrust::unique_copy` using `thrust::transform_iterator` and benchmarked it against the original implementation:

see [thrust_unique_benchmark.cu](https://gist.github.com/dachziegel/191957d90aca8eafda32)

When running on Ubuntu 14.04, CUDA 7 and a GTX 680, this test case outputs:

    original: 3350407 microseconds
    new_impl: 2426929 microseconds
    new_impl is 27.5632 % faster

Would you be interested in a pull request?

**Comment by jaredhoberock** [comment]
It sounds interesting. You might try avoiding [this single-element copy](https://gist.github.com/dachziegel/191957d90aca8eafda32#file-thrust_unique_benchmark-cu-L65) by sending along a counting iterator. It might make a difference to the performance.

**Comment by dachziegel** [comment]
Yes, your idea (`new_impl_2`) is slightly faster and much simpler to implement: [thrust_unique_benchmark_v2.cu](https://gist.github.com/dachziegel/38764693902b71dcd861)

    original  : 3359968 microseconds
    new_impl  : 2424859 microseconds
    new_impl_2: 2410922 microseconds
    new_impl   is 27.8309 % faster than original
    new_impl_2 is 28.2457 % faster than original

I had something similar in mind, but did not like the `if` for the first element :)

Should I prepare the pull request?

**Comment by jaredhoberock** [comment]
Fixed by #679
