### ISSUE TITLE
Assert inside __device__ code fails to work on mac

### ISSUE THREAD

**Issue by egaburov** [thrust/thrust#682]
Reproducer:

    $ cat bug.cu
    #include <thrust/iterator/counting_iterator.h>
    #include <thrust/device_vector.h>
    
    struct bug_functor {
      __host__ __device__   void operator()(int idx) {    assert(idx >= 0); }
    };
    
    int main(void) {
      thrust::for_each(thrust::counting_iterator<int>(0), thrust::counting_iterator<int>(128),bug_functor());
      return 0;
    }

Linux [compiled with master branch]

    $ nvcc --version
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2015 NVIDIA Corporation
    Built on Thu_May__7_00:35:41_CDT_2015
    Cuda compilation tools, release 7.5, V7.5.6
    $ nvcc ~/bug.cu -I. && > ./a.out
    [no error]

OSX [compiled with master branch]

    $ nvcc --version
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2015 NVIDIA Corporation
    Built on Fri_Jul_10_14:08:51_CDT_2015
    Cuda compilation tools, release 7.5, V7.5.13
    $ nvcc ~/bug.cu -I. && ./a.out
    libc++abi.dylib: terminating with uncaught exception of type thrust::system::system_error: function_attributes(): after cudaFuncGetAttributes: OS call failed or operation not supported on this OS
    Abort trap: 6

**Comment by jaredhoberock** [comment]
Hi Evghenii,
Why are you reporting this against Thrust? Does the assert work in a normal CUDA kernel?

**Comment by egaburov** [comment]
Good question, I got so caught up in thrust error message, that didn't think to check CUDA. The assert doesn't work in CUDA kernel. Getting launch failure with the following error: `launch failure: OS call failed or operation not supported on this OS`.

I should've read the manual which states:

"Assertion is only supported by devices of compute capability 2.x and higher. It is not supported on MacOS, regardless of the device, and loading a module that references the assert function on Mac OS will fail."

Pardon me, my bad.

**Comment by jaredhoberock** [comment]
Thanks Evghenii. I've filed an RFE against the compiler requesting them to refuse to compile codes like these.
