### ISSUE TITLE
older nvcc doesn't recognize nv_exec_check_disable

### ISSUE THREAD

**Issue by jaredhoberock** [thrust/thrust#688]
Since older nvcc doesn't recognize `#pragma nv_exec_check_disable`, old warnings and errors may appear if users upgrade Thrust to 1.8.2 but don't upgrade their compiler.

This fix is to apply both pragmas: older nvcc will ignore the newer one, and newer nvcc will recognize both.

**Comment by jaredhoberock** [comment]
@egaburov: I noticed this issue which prompted the use of both `#pragma`s even if they are redundant.

We might need to reinsert the use of `#pragma hd_warning_disable` so that we don't break user code using older `nvcc` with Thrust 1.8.3.

Maybe we could switch between the two pragmas depending on the version of `nvcc`? What do you think?

**Comment by egaburov** [comment]
I see. Which nvcc version you consider older?

If we want to support older nvcc, we need to restore hd_warnings_disable, but the macro definition either needs to be changes, since it expands macro in one line, or we need to define it based on NVCC version. 

e.g.

    #define __exec_check_disable \
    #pragma  nv_exec_check_disable \
    #pragma  hd_warning_disable

And 

    __exec_check_disable

expands to (`g++ -E macro.cpp`)

    #pragma nv_exec_check_disable #pragma hd_warning_disable

Any idea how to rewrite the macro to make it expand to

    #pragma nv_exec_check_disable 
    #pragma hd_warning_disable

**Comment by jaredhoberock** [comment]
> Which nvcc version do you consider older?

It would be the latest version of nvcc which did not support `nv_exec_check_disable`. I'm worried about removing support (i.e., new warnings and errors) in a subminor release. I think it's OK to do this for the master branch, though.

I thought that inserting the `\` would insert a new line, but I guess not. Maybe there's not a way to introduce a newline in a macro definition?

I think we should find out which version of NVCC introduced `nv_exec_check_disable`, and then make the definition of `__thrust_exec_check_disable__` conditional based on NVCC version.

**Comment by egaburov** [comment]
Apparently in it is not possible to add a newline to a macro definition; they are all expanded into a single line. I am sending PR which select correct pragma based on cuda version.
