### ISSUE TITLE
can't retrieve my device after bad_alloc exception

### ISSUE THREAD

**Issue by TikolocheGitHub** [thrust/thrust#696]
The following program does 3 successive calls to the "test" function where a few thrust operations are executed. Each one of these 3 calls provides a different size to the manipulated arrays:

* 3,000 elements for the first call;
* 300,000,000 for the second call;
* 3,000 again for the third call.

The second call is expected to fail with a bad alloc, but the third one should be successful (as is the first one) if I properly cleaned up the status of my GPU with `cudaReset` and `cudaSetDevice`. But it also fails. Moreover, successive calls would also result in a failure. I have to end my process and restart it to be able to operate the device again.

Here is my example code:

```
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <stdio.h>
#include <cuda.h>
#include <thrust/system_error.h>
#include <thrust/device_vector.h>
#include <thrust/sort.h>
#include <thrust/execution_policy.h>

#define CUDA_CALL(x)do { if((x) != cudaSuccess) { return -11;}} while(0)

typedef typename thrust::device_vector<size_t>  tDevVecInt;
typedef typename thrust::device_vector<float>   tDevVecFlt;

struct modSim : public thrust::unary_function<int, int>  
{
    int szMat;
    int p;
    modSim(int in1, int in2)
    {
        this->p = in1;
        this->szMat = in2;
    }
    __host__ __device__ int operator()(const int &x) 
    {
        return (x/szMat)*p+(x%p);
    }
};

 int test(size_t szData)
{
    modSim moduloCol(3, 33);
    CUDA_CALL(cudaSetDevice(0));
    try
    {
        tDevVecFlt devRand(szData);
        tDevVecInt devIndices(szData);
        tDevVecFlt devData(szData);
        thrust::sequence(devRand.begin(), devRand.end());
        thrust::tabulate(devIndices.begin(), devIndices.end(), moduloCol); 
        thrust::sort_by_key(devIndices.begin(), devIndices.end(), devRand.begin()); 
    }
    catch(std::bad_alloc &e)
    {
        std::cout << e.what() << std::endl;
        CUDA_CALL(cudaDeviceReset());
        CUDA_CALL(cudaSetDevice(0));
        return -3;
    }
    catch(thrust::system_error &e)
    {
        std::cout << e.what() << std::endl;
        CUDA_CALL(cudaDeviceReset());
        CUDA_CALL(cudaSetDevice(0));
        return -2;
    }
    CUDA_CALL(cudaDeviceReset());
    return 0;   
}

int main(void)
{
    size_t n = 3000;
    int retVal = test(n);
    std::cout << retVal << std::endl;
    n = 300000000;
    retVal = test(n);
    std::cout << retVal << std::endl;
    n = 3000;
    retVal = test(n);
    std::cout << retVal << std::endl;
    return(0);
}
```

Here is my setup:

 * Windows 8;
 *  NVIDIA GeForce 820m with 2GB dedicated VRAM;
 * CUDA 7.0;
 * Command line for compilation: $nvcc -arch=compute_20 test.cu -run

And here is the output I get:

```
0
bad allocation: out of memory
-3
after cub_::DeviceRadixSort::SortPairs(1): out of memory
-2
```

As mentioned above, the third call shouldn't have failed as it is identical to the successful first call.
This failure seems to be a consequence of the previous call (the one that issued a bad alloc) but I cleaned everything up with a `cudaDeviceReset()` and a `cudaSetDevice()` so the device should be available again.

**Comment by jaredhoberock** [comment]
Thanks for the report. I can reproduce the behavior, but I can't explain it.

My feeling is that this is probably an issue with `cudaDeviceReset` or the CUDA runtime more generally. To my knowledge, there's no way for Thrust's implementation to do something that would cause `cudaDeviceReset` to behave strangely.

**Comment by TikolocheGitHub** [comment]
Ok thanks for your comment! :)
It's good to hear you can reproduce it.I was turning mad on that one!

Do you mean I should report somewhere else on the general CUDA side or do you guys know each other?

**Comment by jaredhoberock** [comment]
Yes, please report it so that you can stay updated on its status. You can access CUDA's bug tracker by becoming a [registered developer](https://developer.nvidia.com/cuda-registered-developer-program). In the bug report, I would frame it as an issue with `cudaDeviceReset` to ensure that a runtime engineer sees it.

For what its worth, I'm not sure a `cudaMalloc` failure requires resetting the entire device -- allocation failures are recoverable, as far as I know.

**Comment by TikolocheGitHub** [comment]
Ok, thanks for the remark, I'll take good note of it.
I just sent a bug report on the CUDA side.

**Comment by jaredhoberock** [comment]
The result of this (which was resolved elsewhere) is that there was no bug in either Thrust or the CUDA runtime. The user needs to explicitly clear the current CUDA error using `cudaGetLastError()` before calling `cudaDeviceReset()`.
