### ISSUE TITLE
cached_device_properties() needs to early exit

### ISSUE THREAD

**Issue by jaredhoberock** [thrust/thrust#703]
From Mike B:

> I think there is a bug [there](https://github.com/thrust/thrust/blob/master/thrust/system/cuda/detail/runtime_introspection.inl#L99).  Shouldn't there be a 'return' statement inside the first 'if' block to avoid reading off the end of the memoization arrays?

**Comment by brycelelbach** [comment]
Well, cached_device_properties seems to have been removed. Not sure that's a good thing, though...

**Comment by brycelelbach** [comment]
Closing this as it's gone, but nvbug 2004717 to figure out why it's gone.
