### ISSUE TITLE
Lambda functions used in protected method generates problem

### ISSUE THREAD

**Issue by gnthibault** [thrust/thrust#726]
Dear developpers,

I may have missed something in the documentation, about the use of thrust::transform with lambda functions, but the following code does not compile [error message is too long to show here]:

//STL
#include <cstdlib>
#include <iostream>

//Thrust
#include <thrust/device_vector.h>
#include <thrust/transform.h>

template<typename T>
class test
{
public:
       	test()=default;
        void testit() { _testit(); };

protected:
	void _testit()
        {
                a = thrust::device_vector<T>(10,4);
                a[2]=16.0;

                for( auto it = a.begin(); it != a.end(); it++)
                {
                        std::cout << "value is now "<< *it << std::endl;
                }

                std::cout << "making computation..."<<std::endl;

                thrust::transform(	a.begin(),
                                a.end(),
                                a.begin(),
                                [] __device__ (T in)->T
                                {
                                return in != 0 ? 1.0/sqrt(in) : 1.0;
                                }
                                );

                for( auto it = a.begin(); it != a.end(); it++)
                {
                        std::cout << "value is now "<< *it << std::endl;
                }
        };
protected:
	thrust::device_vector<T> a;
};

int main( int argc, char* argv[] )
{
        test<float> a;
        a.testit();
        return EXIT_SUCCESS;
}

details:
nvcc version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Thu_May__7_00:35:41_CDT_2015
Cuda compilation tools, release 7.5, V7.5.6

gcc version:
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

thrust version:
a7f2eb214b230d76525264d9738792b20f69c3f0
1.8.2-80-ga7f2eb2

compile command:
nvcc ./test.cu --std=c++11 --expt-extended-lambda -o test

When using a public method, the problem does not occur.

thank you in advance for your help and sorry if I wrote a wrong code.

**Comment by egaburov** [comment]
This is a restriction of the device lambda. From CUDA C Programming guide [1]:

... If the enclosing function is a class member, then the following conditions must be satisfied:
* All classes enclosing the member function must have a name.
* The member function must not have private or protected access within its parent class.
* All enclosing classes must not have private or protected access within their respective parent classes.

.. [1] http://docs.nvidia.com/cuda/cuda-c-programming-guide/#device-lambda-restrictions

**Comment by gnthibault** [comment]
Thank you very much for the link, I wasn't aware of this limitation of cuda.
Now I wonder if it will ever be possible to overcome that problem in future cuda release...

Although it does not seems to be a good practice, I will probably add some public method to my class to overcome the problem for now.
