### ISSUE TITLE
 thrust/examples/histogram.cu crashes

### ISSUE THREAD

**Issue by kandel3** [thrust/thrust#760]
Made a new CUDA 7.5 project in MSVC2013 and copy and pasted the histogram.cu example.

I get the following error:

> Unhandled exception at 0x00007FFA64A4D180 (nvcuda.dll) in thrust_histograms.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Stack trace is quite dense but fails at 
`std::cout << "Dense Histogram" << std::endl;`

Can anybody reproduce this?

By the way we use this machine for most development work and haven't had any other trouble.

**Comment by brycelelbach** [comment]
There is not enough information to act on this. If this is still a problem for you, please provide:

- A minimal test case; e.g. a complete, standalone program that is as small as possible and has few/no dependencies on other software.
- The entire sequence of commands/actions that reproduce the bug (using the minimal test case).
- The unabbreviated outputs of those commands/actions including files, stdout/stderr and logs.
- A description of the environment where the problem occurs (type and version of the hardware, OS, kernel, compiler and any other relevant software).

**Comment by brycelelbach** [comment]
Closing this for now. Please reopen if this is still an issue.
