### ISSUE TITLE
Copy results back via pinned memory?

### ISSUE THREAD

**Issue by eglaser77** [thrust/thrust#762]
Is there any way to get Thrust calls that return values to the host (i.e. thrust::reduce, thrust::unique, thrust::minmax_element) to copy back to pinned memory? I.e. consider a thrust::reduce call that reduces a vector of ints down to a single int. Is there any way for me to allocate an int in pinned memory and have the final cudaMemcpyAsync (host->device) copy to that pinned memory location? 

It is my understanding that in addition to the superior bandwidth of pinned memory transfers (granted the results coming back are quite small, usually a single value or pointer), overlapped copy and kernel execution is only possible when copies are done using pinned memory.

**Comment by brycelelbach** [comment]
I think the answer's gonna be no for this - we have UVM now on the latest hardware, so (IIUC) there's not much of a use for pinned memory. I don't think I want to invest time on adding support for something that's (effectively) legacy.

Sorry!

**Comment by brycelelbach** [comment]
Feel free to re-open, though, if you disagree.
