### ISSUE TITLE
float3_optimization benchmark's "fast" kernel returns references to stack memory

### ISSUE THREAD

**Issue by jlebar** [thrust/thrust#769]
template <typename T>                                                                            
    struct rotate_tuple 
    {   
        template <typename Tuple>
        __host__ __device__                                                                          
        Tuple operator()(const Tuple& t) const                                                       
        {
            T x = thrust::get<0>(t);                                                                 
            T y = thrust::get<1>(t);
            T z = thrust::get<2>(t);                                                                 
        
            T rx = 0.36f*x +  0.48f*y + -0.80f*z;                                                    
            T ry =-0.80f*x +  0.60f*y +  0.00f*z;                                                    
            T rz = 0.48f*x +  0.64f*y +  0.60f*z;                                                    
        
            return Tuple(rx, ry, rz);
        }
    };

What is Tuple?  It looks like it's a `<float, float, float>`, but in reality, it's a `<float&, float&, float&>`.  You can see this by trying to `return Tuple(0.0f, 0.0f, 0.0f);`:

> candidate constructor not viable: expects an l-value for 1st argument

So we're returning references to rx, ry, and rz, which is of course no good.  As a result of the ub, clang optimizes away the whole body of this kernel.

It might be worth running the thrust test suite and benchmark suite under {a,m,ub}san; I think it would have caught this.

Not sending a patch because I'm not actually sure how to fix this.  :)

**Comment by egaburov** [comment]
Try this: return `thrust::make_tuple(rx,rx,tz)` and make return type `thrust::tuple<T,T,T>`, e.g.

```
template <typename T>                                                                            
struct rotate_tuple 
{   
    template <typename Tuple>
    __host__ __device__                                                                          
    thrust::tuple<T,T,T> operator()(const Tuple& t) const                                                       
    {
        T x = thrust::get<0>(t);                                                                 
        T y = thrust::get<1>(t);
        T z = thrust::get<2>(t);                                                                 

        T rx = 0.36f*x +  0.48f*y + -0.80f*z;                                                    
        T ry =-0.80f*x +  0.60f*y +  0.00f*z;                                                    
        T rz = 0.48f*x +  0.64f*y +  0.60f*z;                                                    

        return thrust::make_tuple(rx, ry, rz);
    }
};
```

**Comment by jlebar** [comment]
Great success!  I will send a PR, thank you.
