### ISSUE TITLE
thrust::min_element with thrust::device crashes on raw pointers

### ISSUE THREAD

**Issue by jaredhoberock** [thrust/thrust#776]
Reported here: http://stackoverflow.com/questions/36608199/cuda-thrust-min-element-crashes

Repro:

```
#include <thrust/extrema.h>
#include <thrust/device_ptr.h>
#include <thrust/execution_policy.h>

uint64_t myvec[] = {1,2,3,4,5};

int main(void)
{   
  uint64_t* dev;    
  cudaMalloc(&dev, 5*sizeof(uint64_t));
  cudaMemcpy(dev,myvec,sizeof(uint64_t)*5,cudaMemcpyHostToDevice);  
  thrust::min_element(thrust::device, dev, dev+5);

  return 0;
}
```

Problem seems to be the `*first` [iterator dereference inside of the generic implementation of `min_element`](https://github.com/thrust/thrust/blob/master/thrust/system/detail/generic/extrema.inl#L175). Probably the same problem exists for `max_element` and `minmax_element`.

Should probably use `get_value(exec, first)` instead of `*first`.

**Comment by jaredhoberock** [comment]
@egaburov: Do you want to look into a fix for this one?

**Comment by egaburov** [comment]
The correct way do accomplish this in Thrust is to cast a raw pointer into the device_ptr, e.g.

```
#include <thrust/extrema.h>
#include <thrust/device_ptr.h>
#include <thrust/execution_policy.h>

uint64_t myvec[] = {1,2,3,4,5};

int main(void)
{   
  uint64_t* dev;    
  cudaMalloc(&dev, 5*sizeof(uint64_t));
  cudaMemcpy(dev,myvec,sizeof(uint64_t)*5,cudaMemcpyHostToDevice); 
  thrust::min_element(thrust::device, thrust::device_pointer_cast(dev), thrust::device_pointer_cast(dev)+5);

  return 0;
}
```

**Comment by egaburov** [comment]
Replacing `*first` with `get_value(exec,first)` dispatches to `thrust::system::detail::generic::get_value` (https://github.com/thrust/thrust/blob/1.8.3/thrust/system/detail/generic/memory.inl#L75) 

However `get_value(derived_cast(exec),first)` appears to work. 

What does `derived_cast` exactly do?

**Comment by egaburov** [comment]
Fixed via https://github.com/thrust/thrust/pull/777
