### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by harrism** [thrust/thrust#781]
In the adjacent difference docs, the comment says "d_data is now..." It should be "d_result is now..."
http://thrust.github.io/doc/group__transformations.html#gaa41d309b53fa03bf13fe35a184148400

~~~~
#include <thrust/adjacent_difference.h>
#include <thrust/functional.h>
#include <thrust/device_vector.h>
#include <thrust/execution_policy.h>
...
int h_data[8] = {1, 2, 1, 2, 1, 2, 1, 2};
thrust::device_vector<int> d_data(h_data, h_data + 8);
thrust::device_vector<int> d_result(8);
thrust::adjacent_difference(thrust::device, d_data.begin(), d_data.end(), d_result.begin(), thrust::plus<int>());
// d_data is now [1, 3, 3, 3, 3, 3, 3, 3]
// ^^^^^^^ should be d_result
~~~~

**Comment by jaredhoberock** [comment]
Thanks Mark, it should be fixed in the header file. It will be corrected in the online documentation when it gets regenerated at the next release.
