### ISSUE TITLE
Move semantic for thrust::device_vector

### ISSUE THREAD

**Issue by gnthibault** [thrust/thrust#784]
Hello everybody, here is the corresponding SO question: http://stackoverflow.com/questions/36942126/move-semantic-for-thrustdevice-vector

I am trying to simplify some code that make improper use of std::shared_ptr for handling objects returned by methods.

To do so, I want to rely on std::move, but I am afraid of the fact that thrust does not seem to handle the move construction properly. I wrote a small piece of code that intend to demonstrate this fact.

Could you tell me if the return value of this code is the one that we should expect from a proper implementation of move construction in thrust::device_vector ?

```
#include <thrust/device_vector.h>
#include <thrust/fill.h>

#include <iostream>
#include <cstdlib>
#include <vector>
#include <string>
#include <utility>
#include <algorithm>

class Foo
{
public:
    Foo() : m_v(1,5555)
    {
        std::cout <<"This is the normal constructor with addr "<<
        thrust::raw_pointer_cast( m_v.data() )<<std::endl;
    }
    virtual ~Foo()=default;

    //Copy constructor
    Foo( const Foo& other) : m_v(other.m_v)
    {
        std::cout <<"This is the copy constructor with addr "<<
        thrust::raw_pointer_cast( m_v.data() )<<std::endl;
    }
    //Move constructor
    Foo( Foo&& other) : m_v(std::move(other.m_v))
    {
        std::cout <<"This is the move constructor with addr "<<
        thrust::raw_pointer_cast( m_v.data() )<<std::endl;
    }
    //Move assignment
    Foo& operator=(Foo&& other)
    {
        m_v = std::move(other.m_v);
        std::cout <<"This is the move assignment operator with addr "<<
            thrust::raw_pointer_cast( m_v.data() )<<std::endl;
        return *this;
    }
    //Assignment operator
    Foo& operator=(const Foo& other)
    {
        m_v = other.m_v;
        std::cout <<"This is the assignment operator with addr "<<
        thrust::raw_pointer_cast( m_v.data() )<<std::endl;
            return *this;
    }
    void fillWithVal( int val )
    {
        thrust::fill(m_v.begin(), m_v.end(), val);
    }
    void printValue() const
    {
        std::for_each(m_v.cbegin(), m_v.cend(), [](int in){std::cout<<in<<std::endl;});
    }
protected:
    thrust::device_vector<int> m_v;
};

Foo GetFoo()
{
    Foo f;
    f.fillWithVal( 255 );
    return std::move(f);
}

//Compile using nvcc -std=c++11 ./main.cu -o ./test
//eventually with -fno-elide-constructors
int main()
{
    std::cout <<"test 0 "<<std::endl;
    Foo f = GetFoo();
    f.printValue();

    return EXIT_SUCCESS;
}
```

The return value is:

```
test 0 
This is the normal constructor with addr 0xd06c00000
This is the move constructor with addr 0xd06c00200
255
```

Why do I get two different addresses ? It looks like there is a new allocation of device_vector, and that the pointer to the raw data is not the same anymore.

I tested a very similar code of pure c++11 host code that make use of std::vector (not shown here) and I got the same value printed out for the raw pointer.

Thank you in advance for your help

**Comment by jaredhoberock** [comment]
I think you're asking if `thrust::device_vector` has a user-defined move constructor. It doesn't. In C++11 mode, as of this post, `thrust::device_vector` has the default compiler-generated move constructor.

**Comment by gnthibault** [comment]
Ok, thank you, I guess, it is impossible to handle it in my class as there is no constructor of std::device_vector that take as input an already allocated cuda memory segment.

Other option, I can modify thrust directly, and make a pull request, would you be interested ?

**Comment by jaredhoberock** [comment]
I think we'd be interested in that kind of contribution. Be aware that in addition to introducing the support for `thrust::device_vector`, we'd require the same functionality across all of Thrust's vector types for consistency. We'd also require documentation for the new functionality as well as unit tests.

**Comment by gnthibault** [comment]
Dear Jared Hoberock
I finally found some time to work on this topic, I did a simple though working implementation + simple unit test, but I don't know if I handled properly thrust philosophy, as is it a C++11 only feature.
Should I make a pull request directly ?

**Comment by gnthibault** [comment]
Here are my notes on the pull request:

I did a very simple, yet working implementation of move semantic, that is not the default c++11 implementation.

Here are some question you may ask:

Why C++11 default implementation is not good ?
 -because it does not initialize the new object with its default constructor, hence, when deleting the other temporary object, weird behaviour can occur, ie, pointer or size of the object moved from can take random values, and we may delete a random pointer.

Why so few modifications ?
 -because the swap operator was already defined in vector_base
 -because device_vector and host_vector does not define their own members attributes.

Why you defined assignment operator in device_vector ?
 -because it wasn't defined before, and because, defining the move assignment operator automatically makes it deleted.

**Comment by brycelelbach** [comment]
Hey,

Which pull request is this?

**Comment by jaredhoberock** [comment]
I think it was this PR: https://github.com/thrust/thrust/pull/798

Since it was merged, I think it's safe to close this bug.
