### ISSUE TITLE
Wiki: Change FAQ about calling Thrust algorithms inside CUDA kernels

### ISSUE THREAD

**Issue by emilmelnikov** [thrust/thrust#794]
`wiki/Frequently-Asked-Questions#functionality`:
> * Can I call Thrust algorithms inside a CUDA kernel?
>   * No, it is not currently possible to call Thrust algorithms inside a \_\_global\_\_ or \_\_device\_\_ function.

`CHANGELOG` (Thrust 1.8.0):
> Users may now invoke Thrust algorithms from CUDA \_\_device\_\_ code ...

**Comment by jaredhoberock** [comment]
Thanks! It's been updated.
