### ISSUE TITLE
execution_policy.hpp equates size_t and int

### ISSUE THREAD

**Issue by clwill** [thrust/thrust#814]
`execution_policy.hpp` and several other files have many instances of

```
typedef int size_type;
```

and `size_type` is later used to return or compare with `size_t` values.

When compiling on MSVC using 64-bit, this generates dozens of warnings about loss of data.

Simply changing these to

```
typedef size_t size_type;
```

solves the problem and compiles/runs on both 32 and 64-bit.

Searching finds this equivalence in 1.8.3 in the following files:

```
- cuda_task.hpp
- execution_policy.hpp
- merge.ini
- reduce.hpp
- scatter.hpp
- temporary_indirect_permutation.h
```

**Comment by jaredhoberock** [comment]
Thanks for the report. Can you post a small, self-contained program that reproduces these warnings and let us know which version of MSVC produces these warnings?

**Comment by clwill** [comment]
Sure, here's a program that does it.

```
#include <thrust/device_vector.h>

int main()
{
    thrust::device_vector<int> test;
    return 0;
}
```

I'm currently using VS 2013, which is MSVC 12. But this will happen in literally any version of MSVC because of the way MS C++ handles the sizes of `int`s in 64-bit.

The C++ standard is pretty rough in this neighborhood and leave the sizes of `int`s up to the compiler designer. MS took a fairly weird approach (IMHO) by leaving `int`s at 32-bits in their 64-bit compiler. But they made that decision a decade or more ago, and they're not going to change it.

See this article: https://msdn.microsoft.com/en-us/library/3b2e7499.aspx which references VS2015, but refers to every version back a decade or more.

The result is that people who equate `int`s and `size_t` get burned. The only/best solution is the one I recommend: using `size_t` as the base type for the internal `size_type` identifier and not `int`.

**Comment by brycelelbach** [comment]
We now compile with warnings as errors internally, so this should be fixed now. But we never hit this particular warning when moving in that direction. Closing for now; re-open if you still hit this after the next release.
