### ISSUE TITLE
Will thrust support partial sort?

### ISSUE THREAD

**Issue by cysin** [thrust/thrust#816]
I need to find the top k values in an array(first k smallest or largest values), so will thrust support partial sort?

**Comment by cbezault** [comment]
I don't think so. See isssue #75.

**Comment by egaburov** [comment]
Would nth_element [1] be sufficient for your purpose?

[1] http://en.cppreference.com/w/cpp/algorithm/nth_element

**Comment by brycelelbach** [comment]
Duplicate of #75. Closing.

Hopefully someday!
