### ISSUE TITLE
gcc unused parameter warnings with -Wextra

### ISSUE THREAD

**Issue by GezzMC** [thrust/thrust#820]
Hi, thanks for the product. I use '-pedantic -Wall -Wextra'. The '-Wextra' is causing these warnings:

E:/D_1/w rk/g_d/gezz/xinc/thrust-1.8.2/thrust/detail/allocator/allocator_traits.inl:181:27: warning: unused parameter 'a' [-Wunused-parameter]
     max_size(const Alloc &a)
     
E:/D_1/w rk/g_d/gezz/xinc/thrust-1.8.2/thrust/device_malloc_allocator.h:143:49: warning: unused parameter 'cnt' [-Wunused-parameter]
     inline void deallocate(pointer p, size_type cnt)

E:/D_1/w rk/g_d/gezz/xinc/thrust-1.8.2/thrust/detail/allocator/allocator_traits.inl:205:19: warning: unused parameter 'a' [-Wunused-parameter]
     system(Alloc &a)

--Thanks again.

**Comment by jaredhoberock** [comment]
Thanks for the report! The master branch should be free of these warnings now.
