### ISSUE TITLE
Is any more efficient way to find segmented max/min than sort and reduce_by_key with max/min

### ISSUE THREAD

**Issue by sh1ng** [thrust/thrust#824]
It's recomended to not use reduce with max/min becuase there's more efficient way
http://stackoverflow.com/questions/7709181/finding-the-maximum-element-value-and-its-position-using-cuda-thrust

I'm curious is any way to do it for when a vector are segmented by key?

Example
values = [1, 2, 3, 4, 5, 6, 7]
keys =    [0, 1, 1  1, 0, 0,  0]
should return(in case of max) positions
[6, 3]

**Comment by egaburov** [comment]
It should be possible to build a solution with reduce_by_key, but given reduce_by_key semantics [1] the output for the input would be [0,3,6]  

[1] https://thrust.github.io/doc/group__reductions.html#gad5623f203f9b3fdcab72481c3913f0e0

**Comment by sh1ng** [comment]
@egaburov In your case I will get pair with 
[0, 3, 6] values as you said
[0, 1, 0] keys.
My initial array could be 100M with 10k segments (indicated by key). So I have to invoke one more operation(probably sort by key) after to reduce it again.
 Or I can start with sort by key and then apply reduce. 

Both approaches don't look efficient and elegant. That why I'm asking. 
If I didn't get your point please explain more precisely.

Thanks

**Comment by egaburov** [comment]
I doubt there is more efficient solution for a general data set. For special cases more efficient solutions could exist; for example, if the keys can only take two values, a solution consisting of partition+reduce will be a lot of faster than sort+reduce.

**Comment by sh1ng** [comment]
So your proposal for generic case is sort_by_key then reduce_by_key with max. Am I correct?

**Comment by brycelelbach** [comment]
Hey,

I don't see anything actionable here for me at a glance; please re-open if you'd like to discuss further.
