### ISSUE TITLE
trivial_copy.inl null pointer reference warnings

### ISSUE THREAD

**Issue by ewanbarr** [thrust/thrust#829]
When importing thrust/copy.h using thrust 1.8.3 (shipped with the CUDA 8 RC) the following warning is generated when compiling (using nvcc V8.0.28 and clang-703.0.31 on OSX 10.11.6). 

```
/usr/local/cuda//bin/../include/thrust/system/cuda/detail/trivial_copy.inl:121:6: warning: reference cannot be bound to dereferenced null
      pointer in well-defined C++ code; pointer may be assumed to always convert to true [-Wundefined-bool-conversion]
if (&exec) {
~~   ^~~~
1 warning generated.
```

Can be reproduced by importing "thrust/copy.h" in any code.

**Comment by egaburov** [comment]
This is already fixed, and the fix will be in Thrust shipped with CUDA8.0. Try branch `cuda-next-release` which has the fix.

**Comment by ewanbarr** [comment]
Great, thanks!
