### ISSUE TITLE
Trouble using thrust complex(double) vector with sinus function

### ISSUE THREAD

**Issue by CuvelierFr** [thrust/thrust#833]
I have some problems  using the `sin` and  `sinh`  functions  on a Thrust complex double vector on the device and on the host  : it's seem like computation is done in float.
With `thrust::device_vector< thrust::complex<double> >` and `thrust::host_vector< thrust::complex<double> >`, I obtain  :
`sin( 1+0i ) == (0.8414709568023682,0)`
with `std::complex<double>` :
`sin( 1+0i ) == ((0.8414709848078965,0))`
and `std::complex<float>` :
`sin( 1+0i ) == (0.8414709568023682,0)`
The error with exact value is ~1e-8 with `thrust::complex<double>`

[stackoverflow description](http://stackoverflow.com/questions/39509864/trouble-using-thrust-complexdouble-vector-with-sinus-function)

[test11.cu.zip](https://github.com/thrust/thrust/files/474985/test11.cu.zip)

**Comment by egaburov** [comment]
Thank you for report.  I confirm the incorrect result returned by Thrust:

Repro output:

```
$ nvcc test11.cu -arch=sm_61 -I../../ -run
Thrust: Computation on GPU device (double)
A:
  (1,0)  (1,1)
B =sin(A):
  (0.8414709568023682,0)  (1.298457622528076,0.6349639296531677)
Thrust: Computation on host (double)
A:
  (1,0)  (1,1)
B =sin(A):
  (0.8414709568023682,0)  (1.298457622528076,0.6349639296531677)
std: Computation (double)
sA:
  (1,0)  (1,1)
sin(sA):
  (0.8414709848078965,0)  (1.298457581415977,0.6349639147847361)
std: Computation (float)
sA:
  (1,0)  (1,1)
sin(sA):
  (0.8414709568023682,0)  (1.298457503318787,0.6349638700485229)
```

Here are the results computed by Mathematica [1]

```
In[1]:= N[Sin[1 + I 0], 20]

Out[1]= 0.84147098480789650665

In[2]:= N[Sin[1 + I 1], 20]

Out[2]= 1.2984575814159772948 + 0.6349639147847361083 I
```


[1] http://www.wolfram.com/mathematica/
