### ISSUE TITLE
thrust/master crashing with "invalid device function" when compiled with CUDA 7.5

### ISSUE THREAD

**Issue by dachziegel** [thrust/thrust#837]
I compiled the following demo code (taken from [this SO question](http://stackoverflow.com/questions/39529838/simple-cuda-thrust-program-fails-initcheck-test)) with **thrust/master** and CUDA 7.5:

```
#include <thrust/device_vector.h>
#include <thrust/extrema.h>

int main(void)
{
    // initialize all elements to 2.0
    thrust::device_vector<float> d_vec(10, 2.0);
    d_vec[7] = 1.0;

    thrust::device_vector<float>::iterator iter =
        thrust::min_element(d_vec.begin(), d_vec.end());
    std::cout << iter - d_vec.begin() << "\n";

    return 0;
}
```

Running yields the following crash:

```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: invalid device function
```
my setup:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Thu_May__7_00:35:41_CDT_2015
Cuda compilation tools, release 7.5, V7.5.6

$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
```

Through `git-bisect` I found out that #835 causes this crash.

**Comment by egaburov** [comment]
Bugger. I only tested #835 with -rdc=true -arch=sm_35 or higher . #835  will fail when used without hear flags. Going to revert change .  Thank yo for report

**Comment by jaredhoberock** [comment]
Thanks @dachziegel and @egaburov, this should be fixed now in master.

**Comment by jnareb** [comment]
I get this error for Thrust v1.8.1 from CUDA SDK 7.5, but only if compiling with `-arch=sm_35`, with or without `-rdc=true` flag. There is no such error when compiling for example with `-arch=sm_30`.

```console
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```
