### ISSUE TITLE
Warnings raised from synchronize.inl

### ISSUE THREAD

**Issue by ewanbarr** [thrust/thrust#839]
Since upgrading to the full CUDA 8.0 release (and associated thrust 1.8.3) I get warning when compiling of the form:

`/usr/local/cuda/include/thrust/system/cuda/detail/synchronize.inl(35): warning: calling a __host__ function("cudaDeviceSynchronize") from a __host__ __device__ function("thrust::system::cuda::detail::synchronize") is not allowed`

**Comment by jaredhoberock** [comment]
Thanks for the report, @ewanbarr. I don't observe this warning on my workstation, but I may be compiling with a different configuration than you have. Could you provide us with a small reproducer program and compiler command line that produces this warning so that we can investigate further?

**Comment by TrueNoob** [comment]
Maybe this will help:
**I have no nvidia.**

From box: https://developer.nvidia.com/cuda-downloads
Windows x86 -> 10

[vs output.txt](https://github.com/thrust/thrust/files/560027/vs.output.txt)

Additional:
Emulation (project properties -> CUDA C/C++ -> Host -> Emulation):
nvcc fatal   : Unknown option 'deviceemu'

`#include <thrust/host_vector.h>
#include <thrust/device_vector.h>
#include <thrust/generate.h>
#include <thrust/sort.h>
#include <thrust/copy.h>

void example1()
{
	using namespace thrust;
	// generate 32M random numbers on the host
	host_vector<int> h_vec(32 << 20);
	generate(h_vec.begin(), h_vec.end(), rand);

	// transfer data to the device
	device_vector<int> d_vec = h_vec;

	// sort data on the device (846M keys per second on GeForec GTX 480)
	sort(d_vec.begin(), d_vec.end());

	// transfer data back to host
	thrust::copy(d_vec.begin(), d_vec.end(), h_vec.begin());
}

int main()
{
	example1();	

	return 0;
}`

**Comment by ewanbarr** [comment]
I can no longer reproduce this warning so I am closing this issue for now and putting it down to user error. If I come across this again I'll reopen the issue.

**Comment by busysteve** [comment]
I get this error too when I build with Nsight.  But not in a shell.

**Comment by bkaraivanov** [comment]
I second busysteve. I get this warning when compiling with Nsight on Windows 10. I use Cuda 8.0 and Thrust 1.8.3.

**Comment by anothercodejunkie** [comment]
I just received this, using nvcc 8.0.61 on Ubuntu. I built gcc version 5.3 in order to compile with nvcc. I am using the dist_1d_thrust program from CUDA for Engineers, compiling from the command line:

#include <thrust/device_vector.h>
#include <thrust/host_vector.h>
#include <thrust/sequence.h>
#include <thrust/transform.h>
#include <math.h>
#include <iostream>

const int N = 64;

using namespace thrust::placeholders;

// Define transformation SqrtOf()( x ) -> sqrt( x )
struct SqrtOf
{
    __host__ __device__
    float operator() ( float x )
    {
        return sqrt( x );
    }
};

int main()
{
    const float ref = 0.5f;
    
    thrust::device_vector< float > dvec_x( N );
    thrust::device_vector< float > dvec_dist( N );
    thrust::sequence( dvec_x.begin(), dvec_x.end() );
    thrust::transform( dvec_x.begin(), dvec_x.end(), dvec_x.begin(), _1 / ( N - 1 ) );
    thrust::transform( dvec_x.begin(), dvec_x.end(), dvec_dist.begin(), ( _1 - ref ) * ( _1 - ref ) );
    thrust::transform( dvec_dist.begin(), dvec_dist.end(), dvec_dist.begin(), SqrtOf() );
    thrust::host_vector< float > h_x = dvec_x;
    thrust::host_vector< float > h_dist = dvec_dist;
    for( int i = 0; i < N; ++i )
    {
        std::cout << "x=" << h_x[ i ] << ", dist=" << h_dist[ i ] << "\n";
    }
    
    return 0;
}
