### ISSUE TITLE
compile error: unknown type name '__host__' from clang++

### ISSUE THREAD

**Issue by trontrytel** [thrust/thrust#845]
The following code does not compile after the changes in THRUST_DEVICE_COMPILER_CLANG detection. (It used to work correctly before)
```
 #define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_CPP
 #include <thrust/system/cpp/vector.h>
 int main()
 {
    thrust::cpp::vector<float> v(44);
 }
```
The system is linux. We tested with clang versions 3.6 and 3.8.1.

**Comment by egaburov** [comment]
Looks like changes in #842 in thrust/detail/config/compiler.h introduced regression.
