### ISSUE TITLE
device_reference.swap() does not compile when the device backend is other than CUDA

### ISSUE THREAD

**Issue by jaredhoberock** [thrust/thrust#855]
First reported in #850. Reproducer:

```
#define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_CPP
#include <thrust/device_vector.h>
#include <thrust/system/cpp/vector.h>
#include <thrust/system/cuda/vector.h>
#include <iostream>

int main(int argc, char** argv)
{
  {
    // test swap device_reference

    thrust::device_vector<int> x(2);
    x[0] = 0;
    x[1] = 1;

    thrust::device_reference<int> a = x.front();

    thrust::device_reference<int> b = x.back();

    a.swap(b);

    assert(x[0] == 1);
    assert(x[1] == 0);
  }

  {
    // test swap cpp::reference

    thrust::cpp::vector<int> x(2);

    thrust::cpp::reference<int> a = x.front();
    x[0] = 0;
    x[1] = 1;

    thrust::cpp::reference<int> b = x.back();

    a.swap(b);

    assert(x[0] == 1);
    assert(x[1] == 0);
  }

  {
    // test swap cuda::reference

    thrust::cuda::vector<int> x(2);
    x[0] = 0;
    x[1] = 1;

    thrust::cuda::reference<int> a = x.front();

    thrust::cuda::reference<int> b = x.back();

    // OK
    a.swap(b);

    assert(x[0] == 1);
    assert(x[1] == 0);
  }

  std::cout << "OK" << std::endl;

  return 0;
}
```

Compiler output:

```
$ nvcc -I. test.cu 
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
./thrust/detail/reference.inl(196): error: more than one instance of function template "thrust::system::detail::generic::iter_swap" matches the argument list:
            function template "void thrust::system::detail::sequential::iter_swap(thrust::system::detail::sequential::tag, Pointer1, Pointer2)"
            function template "void thrust::system::detail::generic::iter_swap(thrust::system::detail::generic::tag, Pointer1, Pointer2)"
            argument types are: (thrust::system::cpp::detail::tag, const thrust::device_ptr<int>, const thrust::device_ptr<int>)
          detected during:
            instantiation of "void thrust::reference<Element, Pointer, Derived>::swap(System *, thrust::reference<Element, Pointer, Derived>::derived_type &) [with Element=int, Pointer=thrust::device_ptr<int>, Derived=thrust::device_reference<int>, System=thrust::host_system_tag]" 
(213): here
            instantiation of "void thrust::reference<Element, Pointer, Derived>::swap(thrust::reference<Element, Pointer, Derived>::derived_type &) [with Element=int, Pointer=thrust::device_ptr<int>, Derived=thrust::device_reference<int>]" 
test.cu(20): here

./thrust/detail/reference.inl(196): error: more than one instance of function template "thrust::system::detail::generic::iter_swap" matches the argument list:
            function template "void thrust::system::detail::sequential::iter_swap(thrust::system::detail::sequential::tag, Pointer1, Pointer2)"
            function template "void thrust::system::detail::generic::iter_swap(thrust::system::detail::generic::tag, Pointer1, Pointer2)"
            argument types are: (thrust::system::cpp::detail::tag, const thrust::system::cpp::pointer<int>, const thrust::system::cpp::pointer<int>)
          detected during:
            instantiation of "void thrust::reference<Element, Pointer, Derived>::swap(System *, thrust::reference<Element, Pointer, Derived>::derived_type &) [with Element=int, Pointer=thrust::system::cpp::pointer<int>, Derived=thrust::system::cpp::reference<int>, System=thrust::host_system_tag]" 
(213): here
            instantiation of "void thrust::reference<Element, Pointer, Derived>::swap(thrust::reference<Element, Pointer, Derived>::derived_type &) [with Element=int, Pointer=thrust::system::cpp::pointer<int>, Derived=thrust::system::cpp::reference<int>]" 
test.cu(37): here

2 errors detected in the compilation of "/tmp/tmpxft_000016fe_00000000-9_test.cpp1.ii".
```

There's some speculation about why the call to `iter_swap()` may be ambiguous in #850 at this [comment](https://github.com/thrust/thrust/issues/850#issuecomment-255924185).

**Comment by jaredhoberock** [comment]
I think the reason it works for CUDA `device_reference` is because there exists a CUDA specialization of `iter_swap()`, while the other backends inherit `sequential::iter_swap()`. Calling `iter_swap()` requires a conversion of an execution policy to a tag type, and it is this conversion which makes choosing between `sequential::iter_swap()` and `generic::iter_swap()` ambiguous.

I think relaxing the `tag` parameter of the `iter_swap()` function to be an execution policy reference would correct this issue, but we ought to try to understand why `iter_swap()` does not already receive an execution policy parameter.

**Comment by jaredhoberock** [comment]
Also, we should introduce a unit test for `device_reference::swap()`. It doesn't look like one exists.

**Comment by egaburov** [comment]
As a data point: commenting line https://github.com/thrust/thrust/blob/master/thrust/detail/reference.inl#L194 makes repro to compile.

**Comment by egaburov** [comment]
> I think relaxing the tag parameter of the iter_swap() function to be an execution policy reference would correct this issue, but we ought to try to understand why iter_swap() does not already receive an execution policy parameter.

Alternatively, specialising iter_swap for each of the remaining backend should solve the problem. It seems to be the least invasive fix.

**Comment by egaburov** [comment]
It appears the issue is due to `thrust::system::detail::generic::tag` ctor, which is templated on its argument: https://github.com/thrust/thrust/blob/master/thrust/system/detail/generic/tag.h#L39 

This construct can accept any argument, other tags are implicitly converted to generic tag, and this results in overload ambiguity.

Adding `explicit` to ctor (c++11) or changing ctor to

```
  __host__ __device__ inline
  tag(const tag &) {}
```

makes the repro compile.

I can't explain though why it compiles with CUDA.

**Comment by egaburov** [comment]
Updated: the repro fails to compile also with `#define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_CUDA`. With fix above, the repro compiles fine with both CUDA and CPP systems. The issue describe above seems to be the likely culprit.

Jared, can you verify?

**Comment by jaredhoberock** [comment]
Thanks @egaburov, I can confirm that change to `generic::tag` makes the error go away. I think this workaround is equivalent to removing `using system::iter_swap` from the body of `reference::swap`. I don't think altering `generic::tag`'s ctor is the right thing to do in this case, because then it will never be a match for the primitives in the `generic` namespace. We want that to happen when there is no other match for `iter_swap`, either to dispatch a generic implementation or to issue a `static_assert`.

I think the right thing to do here is to intercept execution policies in primitives like `iter_swap` instead of tags. There are a few of these primitives like `iter_swap` that act on individual elements instead of ranges of elements like `for_each` do. These rationale behind these primitives receiving tags is due to the idea is that we needn't access an execution policy to dispatch something like `iter_swap` versus `for_each`. I think this reasoning is flawed due to this error we've uncovered, and also due to the fact that `assign_value` and `get_value` both take execution polices instead of tags, and they are in the same boat.

If we are contemplating workarounds, I think the least invasive thing to do would be to comment out `using generic::iter_swap` from the body of `reference::swap`. This will solve `swap`'s problem for all of Thrust's backends, as well as user-defined backends that may exist in the wild.

Here's my proposal:

  1. let's workaround the problem in the short term by commenting out the `using` line from `reference::swap`.
  2. let's investigate what happens when we relax `iter_swap`'s parameter from a tag to an execution policy like the other primitives mentioned in `generic/system/memory`.

What do you think?

**Comment by egaburov** [comment]
Sounds good to me.

What I don't understand though is why do we need a generic version whose sole purpose is to generate a compilation error if there is no match? Case at hand, just remove generic implementation `iter_swap`, and compiler naturally will complain if there is no match. Same applies to others.

**Comment by jaredhoberock** [comment]
I think the original idea was to eventually replace the `THRUST_STATIC_ASSERT` found inside the unimplemented generic primitives with a `static_assert` with a more informative error message.

**Comment by brycelelbach** [comment]
Jared, is this implemented somewhere? What's the status?

**Comment by jaredhoberock** [comment]
@brycelelbach: It's been a long time, but the proposed fix seems to be implemented in this PR: https://github.com/thrust/thrust/pull/859

I think the status is that the PR simply needs to be integrated.

**Comment by brycelelbach** [comment]
K, thanks!

Integration task tracked in nvbug 2004661.
