### ISSUE TITLE
How to specify the first parameter 'exec' of function thrust::sort(exec, first, last)

### ISSUE THREAD

**Issue by JacobZhu** [thrust/thrust#866]
How exactly do I specify the first parameter 'exec' of the function:
template<typename DerivedPolicy, typename RandomAccessIterator>
__host__ __device__
  void sort(const thrust::detail::execution_policy_base<DerivedPolicy> &exec,
            RandomAccessIterator first,
            RandomAccessIterator last);
I cannot specify either thrust::host or thrust::device to the first parameter, since they are not defined.

**Comment by egaburov** [comment]
Please make sure that <thrust/execution_policy.h> is included. If this still doesn't work, please post your reproducer code with the reproductions steps. Thanks

**Comment by JacobZhu** [comment]
@egaburov thank you very much, problem solved, I was confused by <thrust/detail/execution_policy.h> file......
