### ISSUE TITLE
It's ok to use Thrust in default cuda 8.0 runtime, but error occurs when use thrust in MFC or Win32 application.

### ISSUE THREAD

**Issue by ningustc** [thrust/thrust#868]
When I program with visual studio 2013, it's ok to use Thrust in CUDA 8.0 runtime console applications, but problem would occur when I use thrust on MFC application. 
Configuration of MFC/Win32 application: 

link->input: cudart.lib 
.cu file is set to compile with cuda/c++

error information:
Error	104	error C2027: use of undefined type 'thrust::detail::STATIC_ASSERTION_FAILURE<false>'	C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\thrust\system\cuda\detail\for_each.inl	109	1

I really need your help for issue!
Or I have to use DLL complied with CUDA runtime.

**Comment by egaburov** [comment]
do you observe similar behavior with 7.5? i'm not sure what is going on, but to help us to debug the issue please provide a self contained reproducer. thanks

**Comment by ningustc** [comment]
I didn't try on 7.5, since I have a GTX 1080 GPU. I use the thrust sample code as follows, and add the code to a MFC/Win32 application, and set the right environment. 

#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <thrust/host_vector.h> 
#include <thrust/device_vector.h> 
#include <thrust/copy.h> 
#include <thrust/fill.h> 
#include <thrust/sequence.h> 
#include <iostream> 

#include <stdio.h>

int thrustTest()
{
	// initialize all ten integers of a device_vector to 1
	thrust::device_vector <int > D(10, 1);
	// set the first seven elements of a vector to 9
	thrust::fill(D.begin(), D.begin() + 7, 9);
	// initialize a host_vector with the first five elements of D
	thrust::host_vector <int > H(D.begin(), D.begin() + 5);
	// set the elements of H to 0, 1, 2, 3, ...
	thrust::sequence(H.begin(), H.end());
	// copy all of H back to the beginning of D
	thrust::copy(H.begin(), H.end(), D.begin());
	// print D
	for (int i = 0; i < D.size(); i++)
		std::cout << "D[" << i << "] = "<< std::endl;
	return 0;
}

This program could run on 8.0 runtime, but for MFC/Win32, this would fail. 

Thanks for your reply.

**Comment by brycelelbach** [comment]
Is this still an issue for you?

**Comment by brycelelbach** [comment]
Hi again. The CUDA backend for Thrust has been substantially rewritten in Thrust 1.9.0 (the version of Thrust in CUDA 9.0). The file you indicated you got an error in (thrust/system/cuda/detail/for_each.inl) is no longer there. Can you please try [the CUDA 9.0 toolkit](https://developer.nvidia.com/cuda-toolkit/whatsnew) and see if you can reproduce your issue? Thanks!

When following up, please provide:

- A minimal test case; e.g. a complete, standalone program that is as small as possible and has few/no dependencies on other software.
- The entire sequence of commands/actions that reproduce the bug (using the minimal test case).
- The unabbreviated outputs of those commands/actions including files, stdout/stderr and logs.
- A description of the environment where the problem occurs (type and version of the hardware, OS, kernel, compiler and any other relevant software).

**Comment by brycelelbach** [comment]
Closing. Please reopen with the requested info if this is still an issue.
