### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by czhu95** [thrust/thrust#877]
Hello,
I currently have difficulties accessing the API documentation for thrust. 
I clicked the links on this page (https://github.com/thrust/thrust/wiki/Documentation) and the site (http://thrust.github.io/) doesn't seem to exist.
Am I the only one having this problem? Could you please help?
Thank you.

**Comment by jaredhoberock** [comment]
All the links on that page seem to work for me.

**Comment by brycelelbach** [comment]
Seems to be fine for me. Please re-open if you're still having issues.
