### ISSUE TITLE
thrust::detail::two_system_copy failed?

### ISSUE THREAD

**Issue by yonglei** [thrust/thrust#881]
### Device Info: 
 cuda devices : 1
  device 0 has compute capability 6.1
  SM count          : 10
  SM clock rate     : 1670 Mhz
  memory clock rate : 4.0 Ghz
  chosen device 0
  device name        : GeForce GTX 1060
  compute capability : 6.1

### Question Description:
I call thrust::detail::two_system_copy to copy data held in vector between host and device, but the target variable is not populated with correct data elementt. what's the point?

![thrust_copy_failed](https://cloud.githubusercontent.com/assets/587580/25474681/a25646fa-2b66-11e7-8842-6e99b06b9932.png)

**Comment by brycelelbach** [comment]
There is not enough information to act on this. If this is still a problem for you, please provide:

- A minimal test case; e.g. a complete, standalone program that is as small as possible and has few/no dependencies on other software.
- The entire sequence of commands/actions that reproduce the bug (using the minimal test case).
- The unabbreviated outputs of those commands/actions including files, stdout/stderr and logs.
- A description of the environment where the problem occurs (type and version of the hardware, OS, kernel, compiler and any other relevant software).

**Comment by brycelelbach** [comment]
Closing. Please reopen with the requested info if this is still an issue.
