### ISSUE TITLE
Linker error when using thrust::copy_if

### ISSUE THREAD

**Issue by bkaraivanov** [thrust/thrust#885]
I am encountering linker error when using copy_if under certain conditions.

- The issue appears very similar to #792.

- I am using CUDA 8.0, Nsight Visual Studio Edition 5.3 with Visual Studio 2015, Thrust v1.8.3, GeForce GTX 1050 Ti with compute capability 6.1 in Windows 10.

- A minimal example, a kernel and companion Visual Studio 2015 solution, is attached below.

[kernel.zip](https://github.com/thrust/thrust/files/1132152/kernel.zip)
[NonCompilingThrust.zip](https://github.com/thrust/thrust/files/1132154/NonCompilingThrust.zip)

- The above minimal example compiles and properly runs if compiled with the field
`Properties -> Configuration Properties -> Cuda C/C++ -> Device -> Code Generation` set to `compute_30,sm_30`, OR with the field `Properties -> Configuration Properties -> Cuda C/C++ -> Common -> Generate Relocatable Device Code` set to `No`.

- However, if I change the above fields to `compute_35,sm_35` AND `Yes (-rdc=true)` respectively, the linker fails with the following message:

`Error LNK2001 unresolved external symbol __fatbinwrap_66_tmpxft_00009eb4_00000000_18_cuda_device_runtime_compute_61_cpp1_ii_8b1a5d37`

- I have also dropped the above code inside a fresh copy of simpleSeparateCompilation from Cuda v8.0 samples using the Visual Studio 2015 solution included in the sample's directory. It compiles and properly runs. However, if I remove `compute_30,sm_30` and all lower compute capabilities from that Visual Studio 2015 solution's properties, compilation fails with the same error as above.

- The issue is important for me because I have actual code that

1. is distributed in several compilation units (files), and so I need to generate relocatable device code.
2. includes a parent kernel that calls a child kernel, a functionality that requires compute capability of 3.5 or above.
3. uses thrust's algorithms like copy_if.

**Comment by brycelelbach** [comment]
I think this is a compiler problem, not a Thrust problem. Could you try reproducing the issue with a CUDA program that doesn't use Thrust?

I've filed a bug internally for this (2004557).

**Comment by BorislavKaraivanov** [comment]
brycelelbach: I compile and run various CUDA programs. Some of them do not use thrust, others do use thrust. The issue does not show up with any of them. It only happened to me with the example I posted. (It happened in real-life code but I provided a minimal example only.) As soon as I comment out the "thrust::copy_if" line it compiles and runs fine. I have asked one of my colleagues to test the above CUDA program on his Windows 10 machine which was set up independently of mine and he reported the exact same problem. To me this is "not-reproducing-without-Thrust" issue. Did you have any other idea how to try to reproduce without Thrust?

**Comment by CNOCycle** [comment]
I believe that #885 and #792 are not bugs from Thrust.

Those two minimal tests work on my machine. (CUDA9.0, VS2015 on Windows 10 / CUDA8.0 gcc-5.4.1 on ubuntu 16.04)

If someone wants to enable dynamic parallelism, you should do the following steps:
1. Properties -> CUDA C/C++ -> Common -> Generate Relocatable Device Code -> Yes (-rdc=true)
2. Properties -> CUDA C/C++ -> Device -> Code Generation -> compute_35,sm_35 (or above)
3. Properties -> Linker -> Input -> Additional Dependencies -> cudadevrt.lib

Because the last step is skipped, your get linking error which is reported by VS.

Make sure that dynamic parallelism works on your machine if the following test can run successfully.
```cpp
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <stdio.h>

__global__ void funcB()
{
    printf("function: funcB()\n");
}
__global__ void funcA()
{
    printf("function: funcA()\n");
    funcB <<<1,1>>>();
}

int main()
{

    printf("function: main()\n");
    funcA <<<1,1>>>();
    return 0;
}
```

I hope that this reply can answer your problem.

**Comment by BorislavKaraivanov** [comment]
@CNOCycle your comment completely solved the issue I was experiencing: both the minimal example and my production code compile and run fine now. All I had to do is follow your point 3 and add cudadevrt.lib
(i.e., Properties -> Linker -> Input -> Additional Dependencies -> cudadevrt.lib) to my projects.

I already had cudart.lib there but only after adding cudadevrt.lib my projects compile. 

And I have to agree that this is not a Thrust issue; it is an issue that is only manifested by Thrust.

Thank you!
