### ISSUE TITLE
Add a "move" event

### ISSUE THREAD

**Issue by Chocanto** [thrust/thrust#890]
Hello !

I would like to fullscreen a new window that I move in a another screen. In order to do that, I need to know when the window has been moved to the new screen and then, after that, send the fullscreen command.

Today I am forced to use the ugly solution : `wait few ms after moving the window`.

Is it possible to get a new `move` event ?

Thank you for your already accomplished hard work !
Anthony

**Comment by jaredhoberock** [comment]
Hi Anthony,
Thanks for the feedback. Is it possible you have the wrong Github project?

**Comment by Chocanto** [comment]
Woops, I am sorry ^^
I am closing this issue.
