### ISSUE TITLE
Memory alignment of thrust::complex

### ISSUE THREAD

**Issue by kqshan** [thrust/thrust#892]
The `thrust::complex` type lacks an explicit alignment specifier, and as a result, the compiler cannot vectorize load/store instructions. 

For example, the following line of kernel code:

    thrust::complex<float> x = X[tIdx];

is compiled to two 32-bit load instructions, rather than a single 64-bit load. This results in strided access to global memory. See also this StackOverflow question, which includes a test case:
https://stackoverflow.com/questions/46965768/optimizing-memory-access-for-complex-numbers

This could by addressed by adding an alignment specifier to the definition of `thrust::complex`, e.g. using the C++11 `alignas` keyword:

    template <typename T>
    struct alignas(2*sizeof(T)) complex { };

**Comment by jaredhoberock** [comment]
Sounds like a reasonable enhancement. My guess is that there are semi-portable ways to do the same thing pre-C++11.

**Comment by brycelelbach** [comment]
This is tracked internally by nvbug 2016340.

**Comment by brycelelbach** [comment]
This will be in the next release.
