### ISSUE TITLE
Is it possible to enable stream per thread in Thrust?

### ISSUE THREAD

**Issue by CNOCycle** [thrust/thrust#893]
This is not a bug. I just want to discuss a CUDA stream issue.

Currently, if users don't specify stream, Thrust puts the function on default stream.

And the behavior of default stream is defined in file `thrust/thrust/system/cuda/detail/execute_on_stream.h`
( this file is removed in CUDA 9.0)
```cpp
__host__ __device__
inline cudaStream_t default_stream()
{
  // XXX we might actually want to use the per-thread default stream instead
  return legacy_stream();
}
```

Is it safe to add a macro switch when compiler detects the flag --default-stream per-thread?
```cpp
__host__ __device__
inline cudaStream_t default_stream()
{
#ifndef STREAM_PER_THREAD
  return legacy_stream();
#else
  return cudaStreamPerThread
#endif
}
```

and `cudaStreamLegacy` and  `cudaStreamPerThread` is defined in file `${CUDA_TOOLKIT}/include/driver_types.h`

I hope that default stream per thread can be enabled in Thrust without modifing any code but add some flags(--default-stream per-thread or -DSTREAM_PER_THREAD) from compiler.

I did a simple test. It works. But there are some stream issues #684, #560.

any suggestion?

**Comment by brycelelbach** [comment]
Stream support in Thrust today is kinda hacked in; longer term, we'll move towards a more explicitly asynchronous model that supports streams better.

This might be fine as a short-term hack, though.

@jaredhoberock, thoughts?

**Comment by brycelelbach** [comment]
Tracked internally as nvbug 2024103.

**Comment by jaredhoberock** [comment]
I don't think Thrust would ever add a hypothetical `STREAM_PER_THREAD` macro, but it may be safe for a user to do in their private version of Thrust. It may or may not be safe to do in general; I'm not sure of the ramifications. In particular, the way that host <-> device copies implicitly block the entire system with the default stream is a important safety mechanism.

There may be a way to enable this behavior nonintrusively using `cuda::par.on(s)`, where `s` would be a special hypothetical token referring to the per-thread stream. Does CUDA make such a token available? I'm not sure.

Failing that, my advice would be to try to make the edit you suggest, and then observe the behavior of the example programs, looking for any failures. If everything works, and your application also works as suggested, then it's probably safe to do.

**Comment by brycelelbach** [comment]
So, @CNOCycle, given @jaredhoberock's thoughts on this, I'm inclined to say "wait for the new asynchronous interfaces in Thrust (which will be awesome)".

Closing for now, but please feel free to re-open.

RE: Jared's question about the per-thread stream - I'm not sure, I checked the CUDA docs briefly and didn't see anything.
