### ISSUE TITLE
Typo in the documentation of `inclusive_scan_by_key`

### ISSUE THREAD

**Issue by HSeo** [thrust/thrust#894]
I am sorry for the tiny indication, but I found some typos in the documentation of Thrust.

At the Segmented Prefix Sums section, 
https://thrust.github.io/doc/group__segmentedprefixsums.html

in all sample codes for inclusive_scan_by_key, data[10] should be vals[10].

**Comment by brycelelbach** [comment]
Will fix. Feel free to send a PR, though.

**Comment by brycelelbach** [comment]
Tracked internally by NVBug 2062280.

**Comment by brycelelbach** [comment]
Fixed.

**Comment by brycelelbach** [comment]
Note that I need to actually learn how to regenerate the doxygen for this to get onto the website.
