### ISSUE TITLE
NVBug 2224607, StackOverflow - Seg fault when dereferencing `reference`s to device data when invoking generic sequential fallback algorithms with stream execution policies

### ISSUE THREAD

**Issue by brycelelbach** [thrust/thrust#922]
We've received two reports that using a stream execution policy with Thrust binary search algorithms (`binary_search`, `upper_bound` and `lower_bound`) leads to a seg fault with CUDA 9.0 or later.

The following test case will reproduce the problem:

```
#include <thrust/binary_search.h>
#include <thrust/device_vector.h>
#include <thrust/execution_policy.h>
#include <thrust/sequence.h>
#include <thrust/system/cuda/execution_policy.h>
#include <cuda_runtime.h>
#include <iostream>

int main(void)
{
    cudaStream_t stream = NULL;
    cudaStreamCreate(&stream);

    thrust::device_vector<int> dev_buff(10);
    thrust::sequence(thrust::cuda::par.on(stream),
        dev_buff.begin(), dev_buff.end()); // <- passed

    auto find = thrust::binary_search(dev_buff.begin(),
        dev_buff.end(), 3); // <- passed
    std::cout << std::boolalpha << find << std::endl; 

    find = thrust::binary_search(thrust::device,
        dev_buff.begin(), dev_buff.end(), 3); // <- passed
    std::cout << find << std::endl;

    find = thrust::binary_search(thrust::cuda::par,
        dev_buff.begin(), dev_buff.end(), 3); // <- passed
    std::cout << find << std::endl;

    /*
    following code caused "Segmentation fault" when used "thrust::cuda::par.on(stream) 
    to thrust::binary_search, thrust::lower_bound and thrust::upper_bound"
    */
    find = thrust::binary_search(thrust::cuda::par.on(stream),
        dev_buff.begin(), dev_buff.end(), 3);
    std::cout << find << std::endl;

    cudaStreamSynchronize(stream);
    cudaStreamDestroy(stream);

    return 0;
}
```

Upon investigation, I discovered there's two problems:

1. (Major problem) The new CUB backend for Thrust introduced in CUDA 9.0 does not have a CUDA parallel implementation of binary search algorithms . That means that it falls back to the sequential implementation, which is terrible!
2. (Minor problem) When the sequential implementation is invoked with iterators to data that lives on the device (ex: `device_vector`), it performs the binary search in serial on the host, accessing the device data via `thrust::reference`. When a stream execution policy is used, something gets corrupted when passing it through the dereference operator of `thrust::reference`. Currently, I don't know why this is happening.

This Issue will track problem 2. Issue #921 will track problem 2. This is NVBug 2224607.

**Comment by allisonvacanti** [comment]
Fix in #1104
