### ISSUE TITLE
:tag

### ISSUE THREAD

**Issue by saullocastro** [thrust/thrust#927]

**Comment by brycelelbach** [comment]
?

**Comment by saullocastro** [comment]
@brycelelbach sorry about that I don't even know how I opened this issue

**Comment by brycelelbach** [comment]
NP.

On Thu, Aug 09, 2018 at 03:06:57AM -0700, saullocastro wrote:
> @brycelelbach sorry about that I don't even know how I opened this issue
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/thrust/thrust/issues/927#issuecomment-411707100


------------------------------------------------------
Bryce Adelstein Lelbach aka wash
ISO C++ Committee Member
CppCon and C++Now Program Chair
Thrust Maintainer, HPX Developer
CUDA Convert and Reformed AVX Junkie

Sleep is for the weak
------------------------------------------------------

-----------------------------------------------------------------------------------
This email message is for the sole use of the intended recipient(s) and may contain
confidential information.  Any unauthorized review, use, disclosure or distribution
is prohibited.  If you are not the intended recipient, please contact the sender by
reply email and destroy all copies of the original message.
-----------------------------------------------------------------------------------
