### ISSUE TITLE
(stable_)sort_by_key returns erroneous associative vector in some cases

### ISSUE THREAD

**Issue by MarsuPila** [thrust/thrust#933]
Hi,

I ran into the issue that (stable_)sort_by_key in some cases returns an erroneous associative vector or vector tuple using thrust::greater_equal as comparator.

In the provided example code the last entry is "3" after the sorting when it should be "35". Now "3" appears twice, while "35" is missing. This does not happen of the comparator is thrust::greater, even though the values in the key are unique, so there shouldn't be a difference between > and >=.

I could reproduce the error with the comparator thrust::greater_equal and one written by myself. Furthermore with the standard and stable sort version, but only if the length of the vectors is 13. (I wouldn't rule out though, that there are other vector lengths resulting in an error.)

Tests with cuda versions 9.0 and 10.0 on a K20 and a Titan V returned concurrent results.

Regards, Marius

And here's the code:
```c++
#include <thrust/copy.h>
#include <thrust/device_vector.h>
#include <thrust/host_vector.h>

#include <iostream>

int main(){
  unsigned int indices[13] = {3, 7, 12, 15, 17, 19, 26, 27, 30, 32, 33, 34, 35};
  float         vals[13]    = {6.01,    5.02,    6.02,    4.05,    4.06,    5.04,
                              6.03,  4.4188, 4.53874, 4.54635, 3.80628, 4.55488, 3.70586};
  const unsigned int nVals = sizeof(indices)/sizeof(*indices);
                                
  thrust::host_vector<unsigned int>   thvIndices(indices, indices+nVals);
  thrust::host_vector<float>           thvVals(vals, vals+nVals);
  thrust::device_vector<unsigned int> tdvIndices = thvIndices;
  thrust::device_vector<float>         tdvVals    = thvVals;


  // output original vectors
  std::cout << std::endl << " initial indices and value vectors: " << std::endl;
  for (unsigned int ii=0; ii<nVals; ii++) std::cout << tdvIndices[ii] << "   " << tdvVals[ii] << std::endl;

  // sort using thrust::greater<float>()
  thrust::stable_sort_by_key(tdvVals.begin(), tdvVals.end(), tdvIndices.begin(), thrust::greater<float>());

  std::cout << std::endl << " after sorting using thrust::greater(): " << std::endl;
  for (unsigned int ii=0; ii<nVals; ii++) std::cout << tdvIndices[ii] << "   " << tdvVals[ii] << std::endl;  

  // reset device vectors
  thrust::copy(thvIndices.begin(), thvIndices.end(), tdvIndices.begin());
  thrust::copy(thvVals.begin(),    thvVals.end(),    tdvVals.begin());
 
  // sort using thrust::greater_equal<float>()
  thrust::stable_sort_by_key(tdvVals.begin(), tdvVals.end(), tdvIndices.begin(), thrust::greater_equal<float>());

  std::cout << std::endl << " after sorting using thrust::greater_equal(): " << std::endl;
  for (unsigned int ii=0; ii<nVals; ii++) std::cout << tdvIndices[ii] << "   " << tdvVals[ii] << std::endl;
  std::cout << std::endl;
 
 return 0;
}
```

**Comment by griwes** [comment]
The bug is in your code, because the comparator you are passing in, `thrust::greater_equal`, does not satisfy the requirements of the algorithm.

Sorting algorithms require a strict weak ordering. It's the same requirement as the [`std::StrictWeakOrdering` from C++20](https://en.cppreference.com/w/cpp/concepts/StrictWeakOrder). For `greater_equal`, the first semantic requirement is not true: `r(1, 1)` is equal to `true`, when it is expected for that to be false.

Whether there's actual equal elements does not matter; the algorithm may use this comparator to create a function for equal comparison - `eq(x, y) = !r(x, y) && !r(y, x)`. The way it fails (or works) when you do not satisfy the semantic requirements is not guaranteed.

**Comment by jaredhoberock** [comment]
This kind of report is common enough that I wrote a function to certify whether or not a comparator is strict weak:

https://github.com/jaredhoberock/is_strict_weak_ordering
