### ISSUE TITLE
Consider .NET support

### ISSUE THREAD

**Issue by jaredhoberock** [thrust/thrust#94]
Originally from Thrust  issue 55 :

Comment 2 by ade.s.miller, Yesterday (18 hours ago)
With VS 2010 you get the following warning if /doc option is set:

c:\cuda\include\driver_types.h(119): warning C4635: XML document comment applied to 'cudaErrorTextureFetchFailed': badly-formed XML: Whitespace is not allowed at this location.

If /clr option is set then Thrust fails to compile. "namespace generic" conflicts with the "generic" keyword used by C++/CLI. I suspect this is by design (PPL etc don't support /CLR either) but it isn't called out in the docs anywhere and is an obviousl thing to try it you want to glue .NET into CUDA via Thrust.
Delete comment Comment 2 by PatricioVidal, Feb 22, 2012
A temporary "ugly" work-around is to re-define "generic" before including the thrust headers:
# define generic _thrust_generic
# include <thrust\device_ptr.h>
# undef generic

Delete comment Comment 3 by PatricioVidal, Feb 22, 2012
Another issue is the warning about the use of secure versions of the CRT functions: 
warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

To prevent this:
# define generic _thrust_generic
# pragma warning(push)
# pragma warning(disable: 4996)
# include <thrust\device_ptr.h>
# pragma warning(pop)
# undef generic

Forwarded from http://code.google.com/p/thrust/issues/detail?id=206

**Comment by brycelelbach** [comment]
Any idea if this is still an issue?

Closing for now.

**Comment by MKoep** [comment]
It's still an issue. Please consider renaming 'generic' since generic is a keyword in C++/CLI
