### ISSUE TITLE
MSVC and alignment of thrust::complex

### ISSUE THREAD

**Issue by endorph-soft** [thrust/thrust#947]
We've just run into a memory alignment issue with MSVC, NVCC and thrust::complex. We've using CUDA Toolkit 10.0.

The storage type for thrust::complex depends on the template parameter and the compiler. For double and float, in NVCC only, it uses the CUDA types float2 and double2. The equivalent code compiled by MVSC will use a generic two-member struct.

The issue is that these definitions have different alignments, which results in Bad Things™ when linking our host code to our device code:
 - NVCC + float2 has 8-byte alignment, whilst MSVC + generic_storage_type<float> has 4-byte alignment.
 - NVCC + double2 has 16-byte alignment, whilst MSVC + generic_storage_type<double> has 8-byte alignment.

The only workaround we have at present is to edit complex.h to add an alignas(2*sizeof(T)) to the definition of generic_storage_type. This guarantees that MSVC and NVCC produce the same alignment. 

I don't know if this was introduced by https://github.com/thrust/thrust/issues/892, but it sounds like that might have changed the alignment?

**Comment by endorph-soft** [comment]
If anyone is interested, I filed this as a bug via the NVIDIA developer program (bug 2509847). No real traction as of yet.

**Comment by endorph-soft** [comment]
This has just been resolved via https://github.com/thrust/thrust/commit/dca67223ddf9b21b96fa85ab3f556ce5f243714d

**Comment by brycelelbach** [comment]
Yah sorry, forgot to close this bug.

Basically, now we just always align to `sizeof(T) * 2`. Be forewarned that on older GCC compilers, using very large `T`s will cause this to break. Shouldn't come up in practice.
