### ISSUE TITLE
Feature Request: Provide Thrust equivalent of std::shuffle 

### ISSUE THREAD

**Issue by jrhemstad** [thrust/thrust#958]
It would be really nice if Thrust provided a device accelerated version of [`std::shuffle`](https://en.cppreference.com/w/cpp/algorithm/random_shuffle).

~This likely requires adding device random engines.~ Silly me, these already exist.

**Comment by jaredhoberock** [comment]
> This likely requires adding device random engines.

Some exist, btw: https://github.com/thrust/thrust/tree/master/thrust/random

**Comment by jrhemstad** [comment]
Closed by https://github.com/thrust/thrust/pull/1085
