### ISSUE TITLE
documentation saying copy_if does not support in-place?

### ISSUE THREAD

**Issue by wukunlinc** [thrust/thrust#980]
From the documentation page: http://thrust.github.io/doc/group__stream__compaction.html#ga695e974946e56f2ecfb20e9ec4fb7cca

"The ranges [first, last) and [result, result + (last - first)) shall not overlap. "

Seems to suggest copy_if shouldn't be used as an in-place operation, so we can't have [first] and [result ] being the same device pointer, right? I tried this and the copy_if results seem to be unaffected when I violate this precondition. Can someone clarify please?

Many thanks.

**Comment by milleniumbug** [comment]
An observation where the code happens to work on a specific version of library, under a specific implementation with particular set of compiler flags on a specific hardware configuration, does not contradict the *contract* (that is, the documentation).

It's similar to driving through the crossroad where a red traffic light indicates you should stop. "The traffic laws say I shall not drive on a red light, but I did, and nothing happened to me."

Mandatory reading https://devblogs.microsoft.com/oldnewthing/?p=31853
