### ISSUE TITLE
not able to use thrust::inner_product

### ISSUE THREAD

**Issue by manasi-t24** [thrust/thrust#986]
Hello,
I am trying to use thrust::inner_product but I am getting the error-  
error: namespace "thrust" has no member "inner_product"

I am using Cuda-8.0 and I checked that its thrust library has the file inner_product.h. I am still getting this error. Any ideas about how to fix this?

Regards,
Manasi

**Comment by griwes** [comment]
Please post a minimal code sample that reproduces the issue. Are you _including_ `<thrust/inner_product.h>`?

Btw. CUDA 8 is a rather old release ;)

**Comment by manasi-t24** [comment]
I had not included the header file.That was rather silly of me. 
And yes, I am aware that Cuda-8.0 is an old release but I am using an application RapidCFD which is compatible with Cuda-8.0 only. So...
Thanks for the quick reply.

Regards,
Manasi
